<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>foto profile</name>
   <tag></tag>
   <elementGuidId>3afead27-c8d1-4063-aaf1-f92ede55f153</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='navbar-brand-centered']/ul/li[6]/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>ec3864de-0bd6-4682-9173-4de7d685fa92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>img/noimage.png</value>
      <webElementGuid>29190ae3-1ac9-4ece-a2c8-25cbc918ab81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navbar-brand-centered&quot;)/ul[@class=&quot;nav navbar-nav&quot;]/li[6]/a[1]/img[1]</value>
      <webElementGuid>2175ec04-a1a7-4210-a454-f1ddea694391</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='navbar-brand-centered']/ul/li[6]/a/img</value>
      <webElementGuid>e53463b8-0153-4b38-a64e-6303317c8964</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[6]/a/img</value>
      <webElementGuid>93a3ab89-8b5d-4384-b37b-9808bf14494e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'img/noimage.png']</value>
      <webElementGuid>b251a5bd-a93d-429c-9f77-6c6c8cefb21a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
