<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>icon - email</name>
   <tag></tag>
   <elementGuidId>074d4bed-aa2e-431d-b609-3d9ad9c31c50</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.glyphicon.glyphicon-envelope</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='contact_form']/fieldset/div[2]/div/div/span/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>1351b85b-f21d-4726-b641-3c74ff78ce43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>glyphicon glyphicon-envelope</value>
      <webElementGuid>48e1e2b2-5d16-44d2-89e8-8209f67ed498</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;contact_form&quot;)/fieldset[1]/div[@class=&quot;form-group&quot;]/div[@class=&quot;col-md-4 inputGroupContainer&quot;]/div[@class=&quot;input-group&quot;]/span[@class=&quot;input-group-addon&quot;]/i[@class=&quot;glyphicon glyphicon-envelope&quot;]</value>
      <webElementGuid>12f70f22-5503-4e44-8c4c-f75a26ecdf11</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='contact_form']/fieldset/div[2]/div/div/span/i</value>
      <webElementGuid>91f30281-bbba-42e7-af5a-954240d4e37b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/span/i</value>
      <webElementGuid>c54e2109-44ec-4f46-b866-2f4e857b67c1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
