<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h3_Pencarian populer</name>
   <tag></tag>
   <elementGuidId>beebf11a-0b96-467b-bede-9cd83eeb379c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='search-container']/div/div/div/h3</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h3.css-k8wueb</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h3</value>
      <webElementGuid>497e8da9-a500-457b-b543-85ecf3c15f58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-k8wueb</value>
      <webElementGuid>b44d9c33-64a7-474b-beef-6ced9c556c63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>hHeaderAutocomPopulerTitle</value>
      <webElementGuid>ab9ebba8-8287-46c6-a364-dafe1d61bf10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pencarian populerRefresh</value>
      <webElementGuid>6f078606-72a3-4565-b309-44b0aba997ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;search-container&quot;)/div[@class=&quot;css-1jn6tgt e1aezlny0&quot;]/div[1]/div[@class=&quot;css-xq97c2 containerDropdown&quot;]/h3[@class=&quot;css-k8wueb&quot;]</value>
      <webElementGuid>c9161ea3-398f-4512-b18f-718326235362</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='search-container']/div/div/div/h3</value>
      <webElementGuid>c75a5855-51a1-46ae-80c9-59456977cab8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kategori'])[1]/following::h3[1]</value>
      <webElementGuid>89815741-2204-4a3c-8f73-f7f634769461</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tokopedia Care'])[1]/following::h3[1]</value>
      <webElementGuid>e64b9ff4-cc4a-4e1a-bd00-f94005721625</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kalung Emas'])[1]/preceding::h3[1]</value>
      <webElementGuid>3114ed4d-3e11-4af1-b8b1-0250a899809e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Pencarian populer']/parent::*</value>
      <webElementGuid>392f4a37-ee06-4cf2-a058-a2e2e5d8f1a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h3</value>
      <webElementGuid>2edfb651-0e44-4b48-89d1-5223275d4b23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h3[(text() = 'Pencarian populerRefresh' or . = 'Pencarian populerRefresh')]</value>
      <webElementGuid>361b80b1-d7e3-46d6-899d-68322fba31fc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
