<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Password terlalu pendek</name>
   <tag></tag>
   <elementGuidId>73f72a86-c463-49ac-b143-6f174caa01b4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b5-InputKataSandi']/span/div/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.pass-text</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>e26526d5-a87d-46bb-b78c-5619c877d52b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pass-text</value>
      <webElementGuid>e9d43791-96f3-4f4a-a902-b1fa6fa835b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Password terlalu pendek</value>
      <webElementGuid>721cfe5f-c05b-429b-8047-7bdaa1025346</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b5-InputKataSandi&quot;)/span[@class=&quot;input-password pass-strength-visible&quot;]/div[@class=&quot;pass-wrapper&quot;]/span[@class=&quot;pass-text&quot;]</value>
      <webElementGuid>a80d17fe-26e7-492b-aece-47efcb0257d0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b5-InputKataSandi']/span/div/span</value>
      <webElementGuid>b42df3b7-ff6c-4970-b526-add29d70ddf6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kata Sandi'])[2]/following::span[2]</value>
      <webElementGuid>7c1fdcbb-40a7-493c-8b89-83cca0ee21fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Perempuan'])[1]/following::span[3]</value>
      <webElementGuid>1cad740c-5de8-4633-92d7-f787122f79b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password harus memiliki minimal 7 karakter dan 1 angka. Contoh : biko1234'])[1]/preceding::span[1]</value>
      <webElementGuid>09dccf87-4934-47bb-aadc-59caa0b9dd2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Minimal 7 karakter dan kombinasi angka. Contoh : Astra345'])[1]/preceding::span[2]</value>
      <webElementGuid>71c5176b-4c65-4d26-86da-b513f35c2c21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Password terlalu pendek']/parent::*</value>
      <webElementGuid>3d09d465-567e-45c6-aba3-763878d232fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/div/span</value>
      <webElementGuid>e9419ffc-1bd5-49cf-be92-546beef202a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Password terlalu pendek' or . = 'Password terlalu pendek')]</value>
      <webElementGuid>58e9d838-7144-47f6-863f-bc6268355761</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
