<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Format email yang dimasukkan belum sesuai</name>
   <tag></tag>
   <elementGuidId>86b4bc78-f9d8-4c70-89e9-7123d3847f86</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b5-b3-Input']/span/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.validation-message</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>60b208e8-4f71-4518-880f-058217d253c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>validation-message</value>
      <webElementGuid>e75cab87-61f6-4a7b-b3a1-40945491c79a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Format email yang dimasukkan belum sesuai. Contoh : biko.maryono@gmail.com</value>
      <webElementGuid>f3800490-3315-4d9f-80d7-eead699479fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b5-b3-Input&quot;)/span[@class=&quot;input-email&quot;]/span[@class=&quot;validation-message&quot;]</value>
      <webElementGuid>6d278ccb-20bb-4717-be07-53eb3a0ca380</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b5-b3-Input']/span/span</value>
      <webElementGuid>04504329-0319-4e48-a789-744fb18b184b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email'])[1]/following::span[2]</value>
      <webElementGuid>836f4f50-3ac0-4019-af25-8d57277f06ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nama Sesuai KTP'])[1]/following::span[4]</value>
      <webElementGuid>a5c52fd1-5b29-468a-b0c8-9190e0aac1f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contoh : biko.maryono@acc.co.id'])[1]/preceding::span[1]</value>
      <webElementGuid>0fa22c78-99c6-44f4-b31f-3d57a201da7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No. Handphone'])[1]/preceding::span[3]</value>
      <webElementGuid>780cc0c7-7a9a-4507-8c17-485764675526</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Format email yang dimasukkan belum sesuai. Contoh : biko.maryono@gmail.com']/parent::*</value>
      <webElementGuid>4bb24c3b-6664-4870-a827-45a755ef5a63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span</value>
      <webElementGuid>9589a941-02d6-4487-9de2-cd153e12bac6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Format email yang dimasukkan belum sesuai. Contoh : biko.maryono@gmail.com' or . = 'Format email yang dimasukkan belum sesuai. Contoh : biko.maryono@gmail.com')]</value>
      <webElementGuid>e35ef654-e680-4b7a-b278-4ce30eba531d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
