<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Nama Lengkap minimal 3 Karakter dan Maksimal 50 Karakter (1)</name>
   <tag></tag>
   <elementGuidId>a6205ebc-e054-4e32-a893-47d5f49e23a4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b5-b2-Input']/span/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.validation-message</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>39f52a8b-dd83-425a-b3d0-b1dd020c3d6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>validation-message</value>
      <webElementGuid>1932ebc2-8d2b-42d4-831d-0316f9ab5dfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Nama Lengkap minimal 3 Karakter dan Maksimal 50 Karakter</value>
      <webElementGuid>f282635c-04ce-4c2d-8d69-bb6bbb32e951</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b5-b2-Input&quot;)/span[@class=&quot;input-text&quot;]/span[@class=&quot;validation-message&quot;]</value>
      <webElementGuid>dfd8b4ea-867e-4379-af5d-080ef772b00f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b5-b2-Input']/span/span</value>
      <webElementGuid>8fbbd97b-1d8e-43fe-b63f-7f1506b52600</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nama Sesuai KTP'])[1]/following::span[2]</value>
      <webElementGuid>e6a33c99-3045-4c37-9b2d-43fbbb8e9e5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Masuk'])[2]/following::span[3]</value>
      <webElementGuid>a7473819-55ed-44c8-8eea-d303974d0c39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email'])[1]/preceding::span[1]</value>
      <webElementGuid>2eeed5db-01ac-497c-ab3c-95932a3f30f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contoh : biko.maryono@acc.co.id'])[1]/preceding::span[3]</value>
      <webElementGuid>6c7fb5ae-482c-4709-8ce9-0369706fa4bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Nama Lengkap minimal 3 Karakter dan Maksimal 50 Karakter']/parent::*</value>
      <webElementGuid>c9330490-440e-433f-806c-0f5eafc9362a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span</value>
      <webElementGuid>9c198155-ced2-4236-9cca-5cecae6eae55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Nama Lengkap minimal 3 Karakter dan Maksimal 50 Karakter' or . = 'Nama Lengkap minimal 3 Karakter dan Maksimal 50 Karakter')]</value>
      <webElementGuid>f6be1fc5-610b-4090-9c6d-e40497a3e514</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
