<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Nomor ponsel Anda Tidak Valid</name>
   <tag></tag>
   <elementGuidId>be811d07-dea3-4100-8b2e-2587523b2d8b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b5-b4-Input']/span/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.validation-message</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>12e5d1dd-f62b-42b6-92f2-f17b24d0de61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>validation-message</value>
      <webElementGuid>7a19035e-e9bc-4ee5-97c2-e630c0b00d97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Nomor ponsel Anda Tidak Valid</value>
      <webElementGuid>891bfd61-1ad6-4c81-902e-e56222e6406b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b5-b4-Input&quot;)/span[@class=&quot;input-tel&quot;]/span[@class=&quot;validation-message&quot;]</value>
      <webElementGuid>97b82ac9-1c0a-407a-9603-c2085316a2f3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b5-b4-Input']/span/span</value>
      <webElementGuid>6d60d3c4-123e-4059-b970-f37cdaa9638d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No. Handphone'])[1]/following::span[2]</value>
      <webElementGuid>76e5ad6e-d5e4-4cfa-97d9-52e9b356def1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contoh : biko.maryono@acc.co.id'])[1]/following::span[4]</value>
      <webElementGuid>7dfeefa8-c755-40be-882e-cc3de840550d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Laki Laki'])[1]/preceding::span[1]</value>
      <webElementGuid>af4d91f5-2ab9-4a84-914c-cf56886e5c47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Perempuan'])[1]/preceding::span[1]</value>
      <webElementGuid>2e4e8300-c8f5-4303-bef9-b71209a00ab9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Nomor ponsel Anda Tidak Valid']/parent::*</value>
      <webElementGuid>9e7e16d6-022e-49e2-a0e1-f008375815dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span</value>
      <webElementGuid>7cff0644-11d0-4f42-a42b-1b9cdb2f4029</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Nomor ponsel Anda Tidak Valid' or . = 'Nomor ponsel Anda Tidak Valid')]</value>
      <webElementGuid>f7b29ce4-46f9-46a3-8258-927c3e24c491</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
