<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Jawa Barat</name>
   <tag></tag>
   <elementGuidId>534493f1-f936-40cb-a7c7-7ea2d03e77dc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b5-ListGroupArea2']/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>6bc8f722-1674-4a1a-a6e0-57db62c3fe7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>list-item</value>
      <webElementGuid>fbac4b14-fe80-402b-95bf-13c5feb6b7f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Jawa Barat</value>
      <webElementGuid>dd5fb245-e126-4919-82dd-817607ee86ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b5-ListGroupArea2&quot;)/div[@class=&quot;list-item&quot;]</value>
      <webElementGuid>16f605c2-7bc9-4e0f-b7ab-96565f8c2ca9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b5-ListGroupArea2']/div[2]</value>
      <webElementGuid>2e316b94-4183-41c2-b727-e8e92c91cd05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DKI Jakarta dan Banten'])[1]/following::div[1]</value>
      <webElementGuid>fd200983-6ab5-4c18-8072-d5c846c4d81f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Harus dipilih!'])[1]/following::div[5]</value>
      <webElementGuid>a5634dcf-3878-4e1d-a969-8b0f2d5ce645</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jawa Tengah dan DIY'])[1]/preceding::div[1]</value>
      <webElementGuid>c3a89858-a8f8-40aa-a4b5-01ae18076ad8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/div/div[2]/div[2]/div/div[2]</value>
      <webElementGuid>b38183d3-e161-48df-8427-3606d2870a68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Jawa Barat' or . = 'Jawa Barat')]</value>
      <webElementGuid>79c5ac0b-9c72-4562-9010-9041cc567f12</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
