<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Password harus memiliki minimal 7 karakter dan 1 angka. Contoh  biko1234</name>
   <tag></tag>
   <elementGuidId>5261f2f4-d5cf-4bc9-8f11-43113eda79a0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b5-InputKataSandi']/span/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.validation-message</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>6e5ef637-16a2-43fa-928c-477aa80157d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>validation-message</value>
      <webElementGuid>c96d1aa7-28a6-4037-ad20-88f44185e83e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Password harus memiliki minimal 7 karakter dan 1 angka. Contoh : biko1234</value>
      <webElementGuid>6e3c25b1-a571-46e9-b5ff-8b64989a69c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b5-InputKataSandi&quot;)/span[@class=&quot;input-password pass-strength-visible&quot;]/span[@class=&quot;validation-message&quot;]</value>
      <webElementGuid>2ac99114-e7db-4806-b1aa-35ebcfe172fd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b5-InputKataSandi']/span/span</value>
      <webElementGuid>a4ba6ce4-854e-41d6-9cda-d94b80415e6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password terlalu pendek'])[1]/following::span[1]</value>
      <webElementGuid>115f848b-a69a-470c-99c9-6c9201357e6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kata Sandi'])[2]/following::span[3]</value>
      <webElementGuid>98d036aa-0d71-4cef-a1cc-4fb93a239f8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Minimal 7 karakter dan kombinasi angka. Contoh : Astra345'])[1]/preceding::span[1]</value>
      <webElementGuid>636b1d8a-c0ac-4692-8299-4d98387c9501</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Konfirmasi Kata Sandi'])[1]/preceding::span[2]</value>
      <webElementGuid>c4bef613-ccdd-43b0-8164-764a51476275</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Password harus memiliki minimal 7 karakter dan 1 angka. Contoh : biko1234']/parent::*</value>
      <webElementGuid>88c5c011-d76f-423b-ae58-fa644e5c7dbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span</value>
      <webElementGuid>f55a66cd-df6f-4fae-8da7-39e8a1bf8cbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Password harus memiliki minimal 7 karakter dan 1 angka. Contoh : biko1234' or . = 'Password harus memiliki minimal 7 karakter dan 1 angka. Contoh : biko1234')]</value>
      <webElementGuid>c76110f6-b115-46cb-97cd-7752b8f6b828</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
