<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Email tidak valid, silahkan cek kembali email anda</name>
   <tag></tag>
   <elementGuidId>abe7c4c7-bf1e-4bb7-87c9-fe8f9000a1a1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b5-b3-Input']/span/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.validation-message</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>ab9db1ea-668e-4f8c-9095-20867940832e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>validation-message</value>
      <webElementGuid>b8e35599-e8cc-4690-858c-311fd65acabc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Email tidak valid, silahkan cek kembali email anda.</value>
      <webElementGuid>2991b1db-e0d8-421f-b698-ed2e4235b6aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b5-b3-Input&quot;)/span[@class=&quot;input-email&quot;]/span[@class=&quot;validation-message&quot;]</value>
      <webElementGuid>94bdce5e-a1ea-4022-9cc6-56180dfe0bab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b5-b3-Input']/span/span</value>
      <webElementGuid>18461d0e-0ed9-413f-a854-3195ca9436ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email'])[1]/following::span[2]</value>
      <webElementGuid>2774d8cd-f6b0-427e-9e49-918f60314690</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nama Sesuai KTP'])[1]/following::span[4]</value>
      <webElementGuid>8a17bfdc-ed47-4697-b37b-440f4a8db75e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contoh : biko.maryono@acc.co.id'])[1]/preceding::span[1]</value>
      <webElementGuid>e3945c91-1820-407d-9de0-5ea22b50bb5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No. Handphone'])[1]/preceding::span[3]</value>
      <webElementGuid>8fa53b28-6595-4adb-863b-116ae0920ebc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Email tidak valid, silahkan cek kembali email anda.']/parent::*</value>
      <webElementGuid>1bfe8a45-1e42-49d1-891b-97d36229bb81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span</value>
      <webElementGuid>7fce7595-33c4-4da3-a619-62922e822264</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Email tidak valid, silahkan cek kembali email anda.' or . = 'Email tidak valid, silahkan cek kembali email anda.')]</value>
      <webElementGuid>ff5363cc-dd65-49dd-8f5a-da461309c4ce</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
