<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Button - Hitung Simulasi</name>
   <tag></tag>
   <elementGuidId>a177b12e-2361-4540-887e-31c57d59678a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='b5-btn_mobilbaru']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b5-btn_mobilbaru</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5226f939-6939-4305-b3ac-06d65ba7e057</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary-mobilbaru OSFillParent</value>
      <webElementGuid>1a207456-dc6c-4819-a723-eeee3f8efbcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2484b7ee-0619-41d2-9a13-9d153dca3a21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b5-btn_mobilbaru</value>
      <webElementGuid>f6317d35-0f62-477c-900e-bffc582ac518</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Hitung Simulasi</value>
      <webElementGuid>2d17ecdc-7995-4e12-a29e-9815a2fe8d5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b5-btn_mobilbaru&quot;)</value>
      <webElementGuid>ffde4328-f252-4b83-ae3e-aefaadf11b17</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='b5-btn_mobilbaru']</value>
      <webElementGuid>cb4997f6-2e79-4cce-af71-887b3782f374</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b5-b6-Column1']/div/div/div[3]/button</value>
      <webElementGuid>e403d44b-565e-49db-8139-c64852c139c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lihat detail asuransi'])[1]/following::button[1]</value>
      <webElementGuid>c1c33347-9af4-4f07-9ac6-a1b4cc29daef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pilih Semua Rekomendasi Asuransi'])[1]/following::button[1]</value>
      <webElementGuid>94a9d921-b80c-43a8-8f5f-3bde4f5e7018</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Angsuran Per Bulan'])[1]/preceding::button[1]</value>
      <webElementGuid>dd65861c-10d8-408d-a4f4-b912b36944c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rp 0'])[1]/preceding::button[1]</value>
      <webElementGuid>7a7f8f13-ce77-4360-a2fb-bf41f359d788</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Hitung Simulasi']/parent::*</value>
      <webElementGuid>3ecbb7da-ceb9-40e4-893e-19a020a7b0ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/button</value>
      <webElementGuid>1e870d10-2544-499a-8c5c-d832a68a46ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'b5-btn_mobilbaru' and (text() = 'Hitung Simulasi' or . = 'Hitung Simulasi')]</value>
      <webElementGuid>6043224f-ade3-43dd-8e74-fbfb492d85e4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
