<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>field - Date of birth</name>
   <tag></tag>
   <elementGuidId>7a65d057-c264-4cf0-93bf-2e480bd3e561</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#datepicker</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='datepicker']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8fc077ef-cffd-42b7-9694-933018bedb22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>dob</value>
      <webElementGuid>b648c0c4-755e-4b38-a156-f6b04cd6e958</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>mm/dd/yy</value>
      <webElementGuid>f44990ea-0c56-48fe-9c98-c6669d5c731e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>7885c039-545d-43db-8190-fa3215b3f284</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f86bbc7a-0b07-4f77-922c-09eba995f96c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>datepicker</value>
      <webElementGuid>47bc72cc-5df3-4ca2-9e59-9d8fd73f7431</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>04/01/2022</value>
      <webElementGuid>680df265-b662-401f-81d9-7ec6f2bc0b5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;datepicker&quot;)</value>
      <webElementGuid>8b8408df-535a-4d08-a4e5-4ff73afae77a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='datepicker']</value>
      <webElementGuid>1879e7de-9b19-4234-aae3-4fd2dd88e307</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='contact_form']/fieldset/div[4]/div/div/input</value>
      <webElementGuid>7030bf12-8944-4402-93d5-85b567facc3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/input</value>
      <webElementGuid>b95276a9-b7d5-4062-972a-07c2ed18e5c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'dob' and @placeholder = 'mm/dd/yy' and @type = 'text' and @id = 'datepicker']</value>
      <webElementGuid>cdf98306-abbc-4cbc-93cc-3b2910b86722</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
