<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>radioButton - All Risk</name>
   <tag></tag>
   <elementGuidId>769c0997-fbee-455d-8797-594e2868e704</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='b5-RadioButton1-input']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b5-RadioButton1-input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>427c6fff-ffcf-4ec1-b59c-7e3f9faf9aef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>ef31217b-1c2b-47b4-89d6-6f9b82bc7a57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b5-RadioButton1-input</value>
      <webElementGuid>144d1839-9395-42ba-b57a-c1aa4c9716f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>radio-button</value>
      <webElementGuid>3c75a1e2-b33e-4ec0-a17a-1c77abfff36a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>b5-RadioGroup1</value>
      <webElementGuid>0ddd0ef3-82fc-43e9-8389-3a156a2653de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>a71c6253-56d0-4f22-b2ae-adc87ba3e89e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b5-RadioButton1-input&quot;)</value>
      <webElementGuid>8179cb32-8312-434f-9755-6ff43bfc80e6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='b5-RadioButton1-input']</value>
      <webElementGuid>fdea0e0f-a1ca-4b15-88a7-41ad09ef914c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b5-RadioButton1']/input</value>
      <webElementGuid>24234bd8-72c3-4d74-9415-068295fa45e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>8a0a087d-bc4c-4b92-9fd6-df24950bb5d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'b5-RadioButton1-input' and @name = 'b5-RadioGroup1']</value>
      <webElementGuid>f0e8149e-0233-4f1f-8959-c0e2f17ee525</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
