<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_ambil_diskon</name>
   <tag></tag>
   <elementGuidId>f10f39e5-a192-4466-864e-dbbec984e518</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='zeus-root']/div/main/div[5]/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.css-6bc98m</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>9a1b90f4-4566-43d6-9ef3-0e8dce40484f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://ecs7.tokopedia.net/img/blog/promo/2022/02/FLOATING-NEW-YEAR-FEB-50KB-150X150-1.gif</value>
      <webElementGuid>bf933c94-8e50-40a2-99d5-a5cd897dd36a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Gamifloating</value>
      <webElementGuid>265cca5a-5dc0-4799-943d-cf8e00dae33f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-6bc98m</value>
      <webElementGuid>1cdedfe4-fc5b-4ebf-ab84-3d200f128c56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;zeus-root&quot;)/div[@class=&quot;css-3lpl5n&quot;]/main[@class=&quot;css-1rhxxyn&quot;]/div[@class=&quot;css-1tqhcc8&quot;]/a[@class=&quot;css-11fn3ru&quot;]/img[@class=&quot;css-6bc98m&quot;]</value>
      <webElementGuid>faf3dc6e-4df7-45af-9cb3-a8dad06ec266</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='zeus-root']/div/main/div[5]/a/img</value>
      <webElementGuid>91faf99c-264b-4657-bb59-db0b525d71bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Gamifloating']</value>
      <webElementGuid>837ef6b9-e8c0-43d4-b426-3b49fe679f1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/a/img</value>
      <webElementGuid>84c245d3-d333-40de-812c-7eeade3d611f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://ecs7.tokopedia.net/img/blog/promo/2022/02/FLOATING-NEW-YEAR-FEB-50KB-150X150-1.gif' and @alt = 'Gamifloating']</value>
      <webElementGuid>21586d9e-64b9-4586-af52-e55c81603c44</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
