<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img - makanan kering</name>
   <tag></tag>
   <elementGuidId>943e06a9-e7a1-40c1-abdc-b65e90039e07</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='zeus-root']/div/main/section/div/div/div/section/div[2]/div/div/div/div[4]/div/a/picture/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>210fcd91-c880-4817-9016-18fb3dfb4053</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://images.tokopedia.net/img/cache/200-square/attachment/2018/8/9/3127195/3127195_e5b3e074-c897-4cf0-9ced-5572d0538e7c.jpg</value>
      <webElementGuid>bff62c6a-abba-45eb-8930-7ad8ccf21a28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;zeus-root&quot;)/div[@class=&quot;css-3lpl5n&quot;]/main[@class=&quot;css-1rhxxyn&quot;]/section[@class=&quot;css-1jllmtg bordered&quot;]/div[@class=&quot;css-1umeb9i&quot;]/div[@class=&quot;css-1ukamyt m24&quot;]/div[@class=&quot;css-1cysb4j even right&quot;]/section[@class=&quot;css-1rbrfo4-unf-card eeeacht0&quot;]/div[@class=&quot;css-1xpribl&quot;]/div[@class=&quot;css-zgsss css-13gzs8c&quot;]/div[@class=&quot;css-ax720z&quot;]/div[@class=&quot;css-15j6m2y carousel&quot;]/div[@class=&quot;css-1vfou0l&quot;]/div[@class=&quot;css-sncotz center&quot;]/a[@class=&quot;css-1vh5p0r&quot;]/picture[@class=&quot;css-r7hr7&quot;]/img[1]</value>
      <webElementGuid>486bc5b3-a4b9-4c14-be88-4af6162a4a7e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='zeus-root']/div/main/section/div/div/div/section/div[2]/div/div/div/div[4]/div/a/picture/img</value>
      <webElementGuid>cc5b0685-e68f-4221-8d35-2640524bf278</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://images.tokopedia.net/img/cache/200-square/attachment/2018/8/9/3127195/3127195_e5b3e074-c897-4cf0-9ced-5572d0538e7c.jpg')]</value>
      <webElementGuid>4cafbdb8-2775-4d34-a7a6-9ac941e5f1eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/a/picture/img</value>
      <webElementGuid>0821ac4c-4194-469e-b13b-5e37652a135a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://images.tokopedia.net/img/cache/200-square/attachment/2018/8/9/3127195/3127195_e5b3e074-c897-4cf0-9ced-5572d0538e7c.jpg']</value>
      <webElementGuid>fa71120f-18fa-422f-8e3c-0cdd7f10ce6c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
