<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_ALL NEW ALPHARD</name>
   <tag></tag>
   <elementGuidId>0417c64a-517c-48de-8e35-35f52a4edc66</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='b5-l2-174_0-txt_namaarea5']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b5-l2-174_0-txt_namaarea5</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>5388d7a4-89d5-465f-91ca-991a4c5cc5dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b5-l2-174_0-txt_namaarea5</value>
      <webElementGuid>312a519d-ae3f-487e-9703-0d1dc140a77d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ALL NEW ALPHARD</value>
      <webElementGuid>b97744d8-2ea3-40f1-8a23-c3403e412f44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b5-l2-174_0-txt_namaarea5&quot;)</value>
      <webElementGuid>38b467cd-5f2e-4b7f-93af-9e71dca52b1e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='b5-l2-174_0-txt_namaarea5']</value>
      <webElementGuid>d12ffbd4-206d-46fa-871a-c843783579b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b5-ListGroupType']/div/span</value>
      <webElementGuid>1bc33eb2-b1e3-461e-8857-bdaf5190880a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tipe'])[1]/following::span[2]</value>
      <webElementGuid>5b03ef7f-67ae-474d-b3fb-f3cb9ad43097</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Brand'])[1]/following::span[3]</value>
      <webElementGuid>12a4c214-6685-4c1b-8322-ab614372302e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ALL NEW ALTIS'])[1]/preceding::span[1]</value>
      <webElementGuid>bfe00c4e-2354-4feb-8cb0-8da08e2bf091</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ALL NEW AVANZA'])[1]/preceding::span[2]</value>
      <webElementGuid>7891db27-d921-4eed-9c69-0d79e582e5d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='ALL NEW ALPHARD']/parent::*</value>
      <webElementGuid>a745d882-4ac7-4a26-a5ec-fb373ba8a670</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/span</value>
      <webElementGuid>f2ac3644-9dae-45ae-9710-e219830e3e4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'b5-l2-174_0-txt_namaarea5' and (text() = 'ALL NEW ALPHARD' or . = 'ALL NEW ALPHARD')]</value>
      <webElementGuid>52303b60-43cd-4f92-9605-ef362292345d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
