<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_TOYOTA</name>
   <tag></tag>
   <elementGuidId>153fd4b1-0eab-4b10-af1a-f4f74d92342c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='b5-l1-167_0-txt_namaarea']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b5-l1-167_0-txt_namaarea</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>28bae38e-1bee-4b69-8906-bbf5b731186a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b5-l1-167_0-txt_namaarea</value>
      <webElementGuid>39549eec-19f8-4cab-a7e1-35dbf716d7a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>TOYOTA</value>
      <webElementGuid>d8a9b2ab-1292-4666-820e-d75e4e8d1120</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b5-l1-167_0-txt_namaarea&quot;)</value>
      <webElementGuid>a4a1d1a9-e765-4e4c-852d-62b1b211be64</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='b5-l1-167_0-txt_namaarea']</value>
      <webElementGuid>f90fb90b-eb02-420a-8aff-9c19b0b670d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b5-ListGroupArea']/div/span</value>
      <webElementGuid>8541cd04-6a72-4501-b175-8aed7148fbda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Harus dipilih!'])[1]/following::span[1]</value>
      <webElementGuid>3937a485-9196-4936-b539-0fb1bfb7c7dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Brand'])[1]/following::span[3]</value>
      <webElementGuid>0cc47447-6c86-45f0-9a4a-dc0550e3ee47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DAIHATSU'])[1]/preceding::span[1]</value>
      <webElementGuid>2b958e85-89cd-4e67-916a-7db2eab5ab71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ISUZU'])[1]/preceding::span[2]</value>
      <webElementGuid>c330e47f-7f5b-427e-81ea-2a8870ae51d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='TOYOTA']/parent::*</value>
      <webElementGuid>31cb51ff-0be8-4d96-974c-d725270c0424</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/span</value>
      <webElementGuid>abcd0e53-d7a7-407c-9d05-e8c5bb8b662c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'b5-l1-167_0-txt_namaarea' and (text() = 'TOYOTA' or . = 'TOYOTA')]</value>
      <webElementGuid>1a86d4d7-b1a6-4954-97d9-6490e48e02c1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
