<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>checkbox - Pilih Semua Rekomendasi Asuransi</name>
   <tag></tag>
   <elementGuidId>6c19f305-d4ed-4293-a274-fcedef233c7f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='b5-Checkbox1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b5-Checkbox1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>922a0c9b-6d44-4230-8278-04102aaedd87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkbox ThemeGrid_MarginGutter</value>
      <webElementGuid>edbe65da-28be-431b-9c2a-1b8396e1be33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>a1914d21-ef6f-4f4b-9f93-b21bce026131</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b5-Checkbox1</value>
      <webElementGuid>abe2a79d-2c08-4d60-8c45-48a381e3e502</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b5-Checkbox1&quot;)</value>
      <webElementGuid>775d844f-a8f8-4735-ab2a-daa3fc6aef89</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='b5-Checkbox1']</value>
      <webElementGuid>c7407b27-4b0a-4ecc-83c4-b2f109f91d78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b5-b6-Column1']/div/div/div[2]/div[10]/div/div/div/span[2]/input</value>
      <webElementGuid>76ccf32f-dc15-4827-873c-d605b6ce5155</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/input</value>
      <webElementGuid>352946ba-7ba8-4819-9f83-1f32947bae1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'b5-Checkbox1']</value>
      <webElementGuid>38d65c1c-43ac-4e75-97d7-3d971f8df90b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
