<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input - Tahun</name>
   <tag></tag>
   <elementGuidId>b58ef2a9-5659-4529-b816-c4d5ebbdb3ef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b5-b10-TitleWrapper']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b5-b10-TitleWrapper</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>58ae58d1-c3a8-453c-9cb0-476263a121f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>section-expandable-title</value>
      <webElementGuid>27375c8b-8a10-4e1b-9671-5b6c291500d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b250aef1-2b62-4b07-ba35-ed3f0fa9c127</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>2b9115ff-676d-458c-ac70-ff15e599cedb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>1e55e3f7-19de-4c47-8f2e-6e00679f6c89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>7cbaa857-657e-4200-b532-c3b46b9d618e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>b5-b10-Content</value>
      <webElementGuid>fda67cce-e47d-4c8a-af70-dfa319dea9fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b5-b10-TitleWrapper</value>
      <webElementGuid>2fa360c4-19a2-436c-9b29-aadb9dc7072d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tahun</value>
      <webElementGuid>a98e678a-68b5-45a0-a5de-258436e9dda9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b5-b10-TitleWrapper&quot;)</value>
      <webElementGuid>cb994207-fe43-4bc7-bcfd-aecbc418e922</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='b5-b10-TitleWrapper']</value>
      <webElementGuid>aae5c7f3-2d13-4149-b08f-247a779336af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b5-b10-SectionItem']/div</value>
      <webElementGuid>9f547a98-03c6-494d-8142-9fd80d58a76c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Model'])[1]/following::div[7]</value>
      <webElementGuid>599683d8-be69-49e0-962d-51b21b661c03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tipe'])[1]/following::div[13]</value>
      <webElementGuid>1c63dfe2-7ea1-4355-8699-fa2f2d82de8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Harga OTR'])[1]/preceding::div[12]</value>
      <webElementGuid>0f05ba3b-d173-4a46-b011-e1957f2630db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[5]/div/div/div/div</value>
      <webElementGuid>5386a3f5-f649-4230-8924-2b8da8d2232e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'b5-b10-TitleWrapper' and (text() = 'Tahun' or . = 'Tahun')]</value>
      <webElementGuid>0d0f2e8d-898a-4565-8ba0-1b2662557c57</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
