<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Bisa pilih alamat pengirimanmu</name>
   <tag></tag>
   <elementGuidId>99cc1467-aae3-4ea2-a3a9-02c2f6acfa46</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//section/div/div/div[2]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.unf-coachmark__next-button.css-64apm5.e1o9jid35</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d23f6019-7716-48d7-ac45-03e1ef20174b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>unf-coachmark__next-button css-64apm5 e1o9jid35</value>
      <webElementGuid>54b73a47-4afa-4d21-86d4-68c0512e8d3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[5]/div[@class=&quot;css-1tfbuoq-unf-coachmark e1o9jid31&quot;]/section[@class=&quot;css-1frsvni-unf-card eeeacht0&quot;]/div[@class=&quot;unf-coachmark__content-wrapper css-8atqhb e1o9jid32&quot;]/div[@class=&quot;unf-coachmark__footer css-1i5hdkt e1o9jid34&quot;]/div[@class=&quot;unf-coachmark__action-wrapper css-1xhj18k e1o9jid33&quot;]/div[@class=&quot;unf-coachmark__next-button css-64apm5 e1o9jid35&quot;]</value>
      <webElementGuid>b6c7233b-4b79-422b-9cfc-6f64a4012bf5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div/div/div[2]/div</value>
      <webElementGuid>6fd66ce6-639d-491d-a273-bf0f081e074b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
