<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>text_Menampilkan</name>
   <tag></tag>
   <elementGuidId>5b0f106d-7d0c-45e6-b9d4-4456ec2b0cf2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='zeus-root']/div/div[2]/div/div[2]/div[2]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.css-8j9pkz</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9ef6b88b-674b-45df-acaa-22468f1d9720</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-8j9pkz</value>
      <webElementGuid>5f05e6b9-2f39-47a4-b736-9a6a71bd6ea8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>dSRPSearchInfo</value>
      <webElementGuid>511e8d52-e8e4-436c-aded-beef776f248b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Menampilkan 1 - 60 barang dari total 15.9jt+ untuk &quot;sepatu&quot;</value>
      <webElementGuid>a2b2d111-7875-440f-b0f2-770f4fe2e452</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;zeus-root&quot;)/div[@class=&quot;css-3lpl5n&quot;]/div[@class=&quot;css-jau1bt&quot;]/div[@class=&quot;css-1c82svt&quot;]/div[@class=&quot;css-rjanld&quot;]/div[@class=&quot;css-w01oz8&quot;]/div[@class=&quot;css-8j9pkz&quot;]</value>
      <webElementGuid>5fbf38c3-f671-4d7a-a919-918b12043c0c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='zeus-root']/div/div[2]/div/div[2]/div[2]/div</value>
      <webElementGuid>b8eaeb05-5a12-49ba-aa66-118982367cf3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Toko'])[1]/following::div[2]</value>
      <webElementGuid>b4a41869-f85e-4c93-8763-b5a93b6cd586</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Produk'])[1]/following::div[2]</value>
      <webElementGuid>a4c1b01e-2507-46e9-89af-6e427697d1d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Urutkan:'])[1]/preceding::div[1]</value>
      <webElementGuid>eea15ec6-fcd1-4f83-9b28-02eb61be9500</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Menampilkan']/parent::*</value>
      <webElementGuid>108bef14-b866-4f81-8e21-03ddb52ed524</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div</value>
      <webElementGuid>ba36c260-443a-4b90-b2b1-73ad62aedf17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Menampilkan 1 - 60 barang dari total 15.9jt+ untuk &quot;sepatu&quot;' or . = 'Menampilkan 1 - 60 barang dari total 15.9jt+ untuk &quot;sepatu&quot;')]</value>
      <webElementGuid>da72312a-fb5e-4a5a-8004-96f9a5e3b1cb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
