<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input - email</name>
   <tag></tag>
   <elementGuidId>2c561ce0-5718-42cd-a0ee-79d230e16d07</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;fld_email&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='fld_email']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6053781f-1689-4fca-b595-117a09cf8ca5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>field</value>
      <webElementGuid>9e8ff839-f8a1-4581-abac-db240884f1dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>fld_email</value>
      <webElementGuid>62abfcf4-6e13-485f-a54a-919f8e29601f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>7482d245-b201-4fc0-a2ec-c9a685f62764</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>myusername@gmail.com</value>
      <webElementGuid>35c23805-64c3-4e1e-a8bc-3b1271739006</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tab-content1&quot;)/form[1]/input[@class=&quot;field&quot;]</value>
      <webElementGuid>c9617432-8482-4966-ac8f-ada8efe79a5d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='fld_email']</value>
      <webElementGuid>6fb73577-a9fc-4720-9d2b-f84982c5d525</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab-content1']/form/input[3]</value>
      <webElementGuid>ef0d294a-fe4f-4a50-9c3a-5f8f50d1c40d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[3]</value>
      <webElementGuid>e0d28c5b-f071-40b6-9f55-d3c1e358972e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'fld_email' and @type = 'email' and @placeholder = 'myusername@gmail.com']</value>
      <webElementGuid>7e1a371e-7e31-4af6-9ccc-3cf70f5c9eb3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
