<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img - keranjang kosong</name>
   <tag></tag>
   <elementGuidId>466f1d12-9607-4da4-b24e-99b7e4bb00b3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='header-main-wrapper']/div[2]/div[3]/div[2]/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;empty-basket&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>399030cb-39ee-48a3-984d-99dbaaba26d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://ecs7.tokopedia.net/assets-unify/il-header-cart-empty.jpg</value>
      <webElementGuid>3fbddacf-fa00-4ccb-acab-b2c7f1dd0487</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>empty-basket</value>
      <webElementGuid>f66af4de-419e-4f4a-8b92-034d4c00ba8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header-main-wrapper&quot;)/div[@class=&quot;css-1s8dqy5 e90swyx2&quot;]/div[@class=&quot;css-1brt7yz&quot;]/div[@class=&quot;css-1yfdnzs efi7olp0&quot;]/div[@class=&quot;css-1wumfmw&quot;]/img[1]</value>
      <webElementGuid>91f51114-1360-4faa-a544-5a0b72249679</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='header-main-wrapper']/div[2]/div[3]/div[2]/div/img</value>
      <webElementGuid>2c379335-581b-4c1f-9d40-af3d5dd0e2c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='empty-basket']</value>
      <webElementGuid>7fb727f0-0cac-4a28-b80f-72db05d577a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/img</value>
      <webElementGuid>b843aa13-b090-43a6-b50e-05c33a4b49b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://ecs7.tokopedia.net/assets-unify/il-header-cart-empty.jpg' and @alt = 'empty-basket']</value>
      <webElementGuid>6c6a5ee7-4fec-4a6f-8d0d-077a8b9c07c3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
