<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Angsuran Per BulanRp 4.040.000TDPRp 30._3403c6</name>
   <tag></tag>
   <elementGuidId>0986f3a2-e61f-44c4-a62f-f5f2bfb36b80</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b5-b6-Column2']/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.full-width.padding-m</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>4abc0801-8124-4c0b-bd14-3131cddc12e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>full-width padding-m</value>
      <webElementGuid>7990cda5-2889-4eda-ba3a-3ce6adf4e4a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Angsuran Per BulanRp 4.040.000TDPRp 30.252.000* Perhitungan bersifat estimasi* Angsuran sudah termasuk asuransi all riskAjukan Pembiayaan</value>
      <webElementGuid>76e5ecf7-e5d5-4e51-bb65-9267ac8a2167</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b5-b6-Column2&quot;)/div[@class=&quot;bg-blue-column right-radius flex-justify-center full-height position-relative&quot;]/div[@class=&quot;full-width padding-m&quot;]</value>
      <webElementGuid>9fdabb70-0c2a-419d-82cb-457ca18b0661</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b5-b6-Column2']/div/div</value>
      <webElementGuid>577e0a8c-9b35-4a54-a070-192e058a89d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hitung Simulasi'])[1]/following::div[3]</value>
      <webElementGuid>d678174e-c5ee-49d7-ab6e-d3a373d4abc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lihat detail asuransi'])[1]/following::div[4]</value>
      <webElementGuid>2d9733c1-14c0-44e5-a3db-c8ee9ddbc2e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div/div/div/div[3]/div/div/div/div/div/div/div/div/div/div[2]/div/div</value>
      <webElementGuid>b0c29092-d0d4-4ad9-8f39-6973ba0b8f7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Angsuran Per BulanRp 4.040.000TDPRp 30.252.000* Perhitungan bersifat estimasi* Angsuran sudah termasuk asuransi all riskAjukan Pembiayaan' or . = 'Angsuran Per BulanRp 4.040.000TDPRp 30.252.000* Perhitungan bersifat estimasi* Angsuran sudah termasuk asuransi all riskAjukan Pembiayaan')]</value>
      <webElementGuid>57c60083-ef96-4621-a98c-f07bb2075b64</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
