<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_24</name>
   <tag></tag>
   <elementGuidId>650269eb-83bc-4b55-a033-a06bbbcddc34</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='b5-l6-172_1-txt_namaarea7']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b5-l6-172_1-txt_namaarea7</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>3e996ed6-0b38-4c45-8028-e7e1e9db38d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b5-l6-172_1-txt_namaarea7</value>
      <webElementGuid>145066c1-3882-4bc0-9e3d-d894d7233a5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>24</value>
      <webElementGuid>2477a179-1d2d-4fa9-9629-409bca9f68d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b5-l6-172_1-txt_namaarea7&quot;)</value>
      <webElementGuid>4fc45d0c-e6cb-4f5e-904c-6b3ca8b724d8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='b5-l6-172_1-txt_namaarea7']</value>
      <webElementGuid>2298d3be-05cf-4c62-a9ef-a5fb23594171</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b5-ListGroupArea5']/div[2]/span</value>
      <webElementGuid>701da9e8-ccfd-4bfb-8ce9-03c53427bf4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tenor'])[1]/following::span[3]</value>
      <webElementGuid>5b0a384a-43b5-4a34-9caf-6e0d36485c84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DP(%)'])[1]/following::span[4]</value>
      <webElementGuid>feac7c86-92d3-4283-a55e-37dda503775c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Area Pengajuan'])[1]/preceding::span[4]</value>
      <webElementGuid>cce53315-82eb-4d30-8b0d-25c748971b39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pilih Semua Rekomendasi Asuransi'])[1]/preceding::span[5]</value>
      <webElementGuid>661ae45c-0307-4584-985e-e513f94e7702</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='24']/parent::*</value>
      <webElementGuid>658937f5-687b-48ee-b93f-425326a315c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div[2]/span</value>
      <webElementGuid>c10e83fd-1aa0-4e48-957d-34d50bf9ad2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'b5-l6-172_1-txt_namaarea7' and (text() = '24' or . = '24')]</value>
      <webElementGuid>bb6a4a04-d8a9-49ee-8f11-66ebbb94d224</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
