<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_1.3 D FMC AT</name>
   <tag></tag>
   <elementGuidId>8edc6ad1-4304-4c42-91df-c118f4d68d8d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='b5-l3-175_0-txt_namaarea6']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b5-l3-175_0-txt_namaarea6</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>074903bc-07a0-43f1-9a58-d3f3a7e2ce7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b5-l3-175_0-txt_namaarea6</value>
      <webElementGuid>af78c46d-87b4-4fff-8026-429fddfc8664</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1.3 D FMC AT</value>
      <webElementGuid>519bd4f0-b234-49fb-9d1d-78271002ece9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b5-l3-175_0-txt_namaarea6&quot;)</value>
      <webElementGuid>f6ec8ce2-86f4-481e-a67f-4aa7b96718a2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='b5-l3-175_0-txt_namaarea6']</value>
      <webElementGuid>56829014-1e98-42e9-9920-cea63394ae41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b5-ListGroupModel']/div/span</value>
      <webElementGuid>3a6fb5e7-9bc1-4740-9e5d-daae47fb3393</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Model'])[1]/following::span[2]</value>
      <webElementGuid>a447d5c6-c224-4829-91fe-89f643514476</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tipe'])[1]/following::span[3]</value>
      <webElementGuid>6df3329a-92cb-4731-b6bc-cc8d34964f48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MT'])[1]/preceding::span[8]</value>
      <webElementGuid>468f0164-f53c-4390-862e-189f4e0e97c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AT'])[1]/preceding::span[9]</value>
      <webElementGuid>9aaef968-32dd-4d44-ab18-fbfa1458d311</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='1.3 D FMC AT']/parent::*</value>
      <webElementGuid>29896ebd-aa4a-42aa-9a7a-ba20bed896b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/span</value>
      <webElementGuid>aec66873-a8e0-40b8-8966-b98ffc53e1f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'b5-l3-175_0-txt_namaarea6' and (text() = '1.3 D FMC AT' or . = '1.3 D FMC AT')]</value>
      <webElementGuid>128dcc34-f5da-400e-9ca9-0813ac139b82</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
