<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Volvo    Saab    Opel    Audi</name>
   <tag></tag>
   <elementGuidId>2513e11b-4cee-491d-be3f-13a16f2bec21</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cars']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cars</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>60617e5f-5965-41a4-8cc8-a24e1fc07454</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cars</value>
      <webElementGuid>2e935a6e-3582-4b8d-9756-8dc8cbd2b602</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cars</value>
      <webElementGuid>000e6a50-f5c7-4ee0-b658-24a7a3df63a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
    Volvo
    Saab
    Opel
    Audi
  </value>
      <webElementGuid>a69c02ef-98f1-462f-98fb-5e077eb8198f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cars&quot;)</value>
      <webElementGuid>17d2001b-c1cd-44be-8f3d-a04cfc7d28ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page w3schools/iframe__iframeResult</value>
      <webElementGuid>2c35fde3-52f1-4a61-b008-ca0b33b31338</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cars']</value>
      <webElementGuid>c4251788-a3b5-433c-a5e5-2c4d1097108d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Choose a car:'])[1]/following::select[1]</value>
      <webElementGuid>972b6f02-8e2f-4c51-aca9-e71d87163a28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='The select element'])[1]/following::select[1]</value>
      <webElementGuid>14f95840-259d-4901-8c21-6021d330860d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'cars', '&quot;', ')')])[1]/preceding::select[1]</value>
      <webElementGuid>09f1172f-1607-4bf4-a24c-9d7e04be474d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>d5e6a840-bc12-4b99-8c23-e4cb0b8e9a75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'cars' and @id = 'cars' and (text() = '
    Volvo
    Saab
    Opel
    Audi
  ' or . = '
    Volvo
    Saab
    Opel
    Audi
  ')]</value>
      <webElementGuid>ae8e576a-86ec-48c0-90b3-b7ef71f8d09c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
