<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Login__txtUserName</name>
   <tag></tag>
   <elementGuidId>596930f4-8c23-42ad-ac24-dd5cd8f52a26</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='_txtUserName']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;_txtUserName&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>03641a15-c0fd-4062-b2a5-67ff21bc7519</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>field</value>
      <webElementGuid>d296b5fe-7beb-4c7b-97b9-a3f83d9d6303</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>_txtUserName</value>
      <webElementGuid>710c48a8-e5c2-4356-9980-6370f4cca423</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1738704b-c15d-4439-a78f-9aabc2ae27d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Username</value>
      <webElementGuid>7776e83e-9822-4643-a393-1fa06e84cfb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tab-content2&quot;)/form[1]/input[@class=&quot;field&quot;]</value>
      <webElementGuid>daaf3ebb-98b5-4788-88ca-26a8e673c520</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='_txtUserName']</value>
      <webElementGuid>20b1d578-853a-4d16-9781-073ee2fe0a71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab-content2']/form/input[2]</value>
      <webElementGuid>fb1167f7-6f9c-412b-a791-5db5cfc159f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div/form/input[2]</value>
      <webElementGuid>aad23de6-cc9f-4693-b573-d617f085237f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = '_txtUserName' and @type = 'text' and @placeholder = 'Username']</value>
      <webElementGuid>71ac931b-3b01-4330-a28f-fd9a56e92ffe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
