<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Ajukan Pembiayaan</name>
   <tag></tag>
   <elementGuidId>19d87d7e-24fc-4f4f-8684-810def0a9360</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='b5-btn_ajukan_mobilbaru']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b5-btn_ajukan_mobilbaru</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2b0c4d69-8db3-4993-809d-d94d2d09abc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary btn-ajukansimulasi-mobil-baru OSFillParent</value>
      <webElementGuid>3e281d87-eae9-434a-8bd3-3b7b9db47c70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e6b64b0d-0a93-4f74-91d9-725de26ec9d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b5-btn_ajukan_mobilbaru</value>
      <webElementGuid>d6136756-630a-47d7-b193-2094ea5f6af4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ajukan Pembiayaan</value>
      <webElementGuid>35f152bd-8654-4a8c-bf01-d32525f38f9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b5-btn_ajukan_mobilbaru&quot;)</value>
      <webElementGuid>11a72d05-672d-4545-9cd6-619dbf8508b5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='b5-btn_ajukan_mobilbaru']</value>
      <webElementGuid>5c7d2af8-40fd-4ad7-9efd-a48d6e133f45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b5-b6-Column2']/div/div/div[3]/button</value>
      <webElementGuid>afaf257c-297c-4928-a611-ab5f6083e7ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='* Perhitungan bersifat estimasi* Angsuran sudah termasuk asuransi all risk'])[1]/following::button[1]</value>
      <webElementGuid>e15e60ee-053d-4587-a260-a658f87307c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rp 36.810.000'])[1]/following::button[1]</value>
      <webElementGuid>80ab475d-2822-4680-883d-0597cae245a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pilihan Mobil Terbaik'])[1]/preceding::button[1]</value>
      <webElementGuid>93c70fc2-91ac-4365-977b-ecf1971df5fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[3]/button</value>
      <webElementGuid>40a76ab6-7a59-4015-a93e-5df2bc236b5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'b5-btn_ajukan_mobilbaru' and (text() = 'Ajukan Pembiayaan' or . = 'Ajukan Pembiayaan')]</value>
      <webElementGuid>2f9661c4-9477-4a12-ab93-98abe485298e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
