<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Guest</name>
   <tag></tag>
   <elementGuidId>b00dd167-8515-4bf1-9982-d307cd484db9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b5-b26-Title']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b5-b26-Title</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>10efe192-c6d2-41b0-87ef-aa51804e87b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tabs-header-tab ph active</value>
      <webElementGuid>e86b291c-0ac7-4ffc-b37f-75f05012d67c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>bfb02a47-3f0d-4d6e-bc0c-037363ec265d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>e46a4860-3bc8-4be6-9401-83abd93ebeda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b5-b26-Title</value>
      <webElementGuid>e49dfb64-5cdc-4273-9dc0-5b5605cb9c9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tab</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>595fdece-a00e-4499-9e44-e0c8c4c1dae5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>tab 1, 1 of 2</value>
      <webElementGuid>67b63bbe-13e7-48c8-a50a-dff559f4c35f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>56893d3f-f84a-42e4-9de6-48b037706e33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Guest</value>
      <webElementGuid>3e52fa9a-9466-45c5-a9fa-792e1899f352</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b5-b26-Title&quot;)</value>
      <webElementGuid>40cb7c90-0a82-4846-9a06-e4926e42507a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='b5-b26-Title']</value>
      <webElementGuid>d71a4a65-e8fb-4a76-a78e-e7f707fbd4d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b5-$b26']/div</value>
      <webElementGuid>8c9b4ae3-fff9-4364-abe1-9565a2a40af0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ajukan sebagai:'])[1]/following::div[6]</value>
      <webElementGuid>a5fb2219-4b07-4041-ab5e-82f7ac49a749</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'b5-b26-Title', '&quot;', ')')])[1]/following::div[21]</value>
      <webElementGuid>13b94714-d5d5-4bfb-982f-60e004754624</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pengguna ACC ONE'])[1]/preceding::div[1]</value>
      <webElementGuid>64dd19bb-865d-49ce-855c-7a89a884f9af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nama Sesuai KTP'])[1]/preceding::div[4]</value>
      <webElementGuid>efa66efe-ab88-4291-a3af-83d1c4c1b951</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Guest']/parent::*</value>
      <webElementGuid>b8ca163d-523e-4a07-ac71-4fcd507ed41d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div/div/div[2]/div/div/div/div[2]/div/div/div/div/div</value>
      <webElementGuid>90f92625-a6cf-4dd7-9f26-e7d2c5f697db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'b5-b26-Title' and (text() = 'Guest' or . = 'Guest')]</value>
      <webElementGuid>dcf941ab-cc21-43de-8a74-0cbd0d46774d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
