<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nama Sesuai KTP_b5-Input_GuestNameVar</name>
   <tag></tag>
   <elementGuidId>7bad539f-9ac6-4c0a-ad2b-9820d9f64b10</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='b5-Input_GuestNameVar']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b5-Input_GuestNameVar</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>be03d570-0bc2-4e2d-a7c9-416217174ae1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control OSFillParent not-valid</value>
      <webElementGuid>da77cd34-d445-472f-929e-11490bf667d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>70a08dd2-f7d2-472c-8d3f-d7154d389d3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>8d9d9fce-7743-4913-bea7-7b3891cfae3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b5-Input_GuestNameVar</value>
      <webElementGuid>c8f48b4c-0093-4e2b-950f-9ce767556cd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b5-Input_GuestNameVar&quot;)</value>
      <webElementGuid>ae18d63d-a8fc-43db-8e0b-dbfeac2f8520</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='b5-Input_GuestNameVar']</value>
      <webElementGuid>07004e5b-c7d1-4dfc-a5a9-99a03d07d648</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b5-b29-Input']/span/input</value>
      <webElementGuid>24212a37-4815-4d20-8515-4f355580da61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div/div/div/div[2]/span/input</value>
      <webElementGuid>9ac4142d-9236-4de4-9158-7ef44aa9d823</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'b5-Input_GuestNameVar']</value>
      <webElementGuid>7bddd1a4-453a-447e-99b4-7adc84f5b0ad</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
