<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_ALL NEW SIRION</name>
   <tag></tag>
   <elementGuidId>7feda527-f157-4b62-9f93-01c9eef64c8e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='b5-l2-174_0-txt_namaarea5']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b5-l2-174_0-txt_namaarea5</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>ddf58e50-274f-42a4-ae0d-221226cef0e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b5-l2-174_0-txt_namaarea5</value>
      <webElementGuid>81329768-d1a8-4705-8a7f-b6c5a5d4a885</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ALL NEW SIRION</value>
      <webElementGuid>1a0eb96f-6401-40b7-b144-ba896c5eb965</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b5-l2-174_0-txt_namaarea5&quot;)</value>
      <webElementGuid>00bc6461-f963-48c8-a0a1-11ebbb37c1bc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='b5-l2-174_0-txt_namaarea5']</value>
      <webElementGuid>358fff3a-d377-4abf-93b5-18da83524951</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b5-ListGroupType']/div/span</value>
      <webElementGuid>b1ead6ec-b53b-4ac5-bf9f-44337f221dfc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Harus dipilih!'])[1]/following::span[1]</value>
      <webElementGuid>185c0e2f-fc82-4aa1-a6b3-6d399c6994ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tipe'])[1]/following::span[3]</value>
      <webElementGuid>36a701fe-f5a7-4346-82e5-2648acc15f9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ALL NEW TERIOS'])[1]/preceding::span[1]</value>
      <webElementGuid>e801b220-d25b-4a80-bb46-82656334943d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='GRAND NEW XENIA'])[1]/preceding::span[2]</value>
      <webElementGuid>5389870e-e920-4482-8df3-657233562f61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='ALL NEW SIRION']/parent::*</value>
      <webElementGuid>c9ee07f5-0e98-4d0d-9673-c61fbd84b44f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/span</value>
      <webElementGuid>6c4a796c-0626-46b3-90c3-9815d4a5dcb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'b5-l2-174_0-txt_namaarea5' and (text() = 'ALL NEW SIRION' or . = 'ALL NEW SIRION')]</value>
      <webElementGuid>2868bfb6-5d23-4b2c-a563-46f7fc61a87a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
