<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_XENIA</name>
   <tag></tag>
   <elementGuidId>07afd77f-8bee-4332-bddb-734377711293</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='b5-l2-174_18-txt_namaarea5']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b5-l2-174_18-txt_namaarea5</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>00ace207-d077-45a0-bb05-912980baba71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b5-l2-174_18-txt_namaarea5</value>
      <webElementGuid>b2f8f1be-77cf-4a8b-aea9-d037149a4123</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>XENIA</value>
      <webElementGuid>f88209b7-b6e2-4dec-a564-5117a02fc2ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b5-l2-174_18-txt_namaarea5&quot;)</value>
      <webElementGuid>7610fe4a-bf23-46b2-93ff-85b1c8fbf5bf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='b5-l2-174_18-txt_namaarea5']</value>
      <webElementGuid>567a545d-fec6-4567-82ff-02c760170c99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b5-ListGroupType']/div[2]/span</value>
      <webElementGuid>8cde50fd-95ab-45b4-b892-17a9174c5646</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='GRAND NEW XENIA'])[1]/following::span[1]</value>
      <webElementGuid>601fb0df-1d35-4b3e-8261-ea19a27fc6fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Harus dipilih!'])[1]/following::span[2]</value>
      <webElementGuid>f895e917-83bb-455f-a13d-7704e733727a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Model'])[1]/preceding::span[1]</value>
      <webElementGuid>f485837a-427a-4a8c-92f4-6e3109eedfbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tahun'])[1]/preceding::span[2]</value>
      <webElementGuid>1e29f815-c397-4e54-94b4-affd234a8e58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='XENIA']/parent::*</value>
      <webElementGuid>33c2d023-9dbe-4792-bf23-08c13ba0b7bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div[2]/span</value>
      <webElementGuid>b1121781-7025-43ad-91d1-547b2e54d064</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'b5-l2-174_18-txt_namaarea5' and (text() = 'XENIA' or . = 'XENIA')]</value>
      <webElementGuid>98f8d454-c56e-4769-a3ff-0dee1c40d93f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
