<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input - UserName</name>
   <tag></tag>
   <elementGuidId>d6471363-584d-441a-9951-8be55d2e1859</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='_txtUserName']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;_txtUserName&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0d0bcac2-d2e5-44e2-8e5e-91a79c1b6e1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>field</value>
      <webElementGuid>8a1812be-a00b-4058-8568-02ddab1c2bf1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>_txtUserName</value>
      <webElementGuid>11977dd4-6011-47d7-8dc5-ac56818eb222</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b6a8b65c-ec23-4c86-bc17-bc3ee7d923bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Username</value>
      <webElementGuid>e8ee2851-d893-416b-8a34-be35dc77321f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tab-content2&quot;)/form[1]/input[@class=&quot;field&quot;]</value>
      <webElementGuid>a62b555e-bdbd-4aeb-a28f-581c66b66444</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='_txtUserName']</value>
      <webElementGuid>c67af70a-a969-4908-89d5-aff85bed0571</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab-content2']/form/input[2]</value>
      <webElementGuid>22e775fc-0c45-491b-a0e8-043494339760</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div/form/input[2]</value>
      <webElementGuid>806fc4e9-311b-4bfe-b606-c8edc73f6835</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = '_txtUserName' and @type = 'text' and @placeholder = 'Username']</value>
      <webElementGuid>60378895-3846-4b01-9279-f4ddeb372666</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
