<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Hitung Simulasi</name>
   <tag></tag>
   <elementGuidId>eb40dca7-db12-40f2-9a9d-64de38e6435d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='b5-btn_mobilbaru']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b5-btn_mobilbaru</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>726450fb-3dca-4372-8668-0a37f78a95b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary-mobilbaru OSFillParent</value>
      <webElementGuid>d3445fa1-3055-4741-8e5e-bc245069d201</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>94eef9c8-e72b-442c-b7b1-2c8ba12b7b3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b5-btn_mobilbaru</value>
      <webElementGuid>3178eb92-75bd-4815-bd69-106431d5bade</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Hitung Simulasi</value>
      <webElementGuid>8ea43a3c-5cd7-4d36-be0e-1394551d6c3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b5-btn_mobilbaru&quot;)</value>
      <webElementGuid>8b81a24d-db54-4566-928b-d687d2748a1a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='b5-btn_mobilbaru']</value>
      <webElementGuid>3ae78a39-a775-44e8-8812-220ddb1a8e00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b5-b6-Column1']/div/div/div[3]/button</value>
      <webElementGuid>c689eb60-b615-4038-86d0-5707f1e491b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lihat detail asuransi'])[1]/following::button[1]</value>
      <webElementGuid>0ebbbc49-1a48-4150-9129-eb49a3d569f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pilih Semua Rekomendasi Asuransi'])[1]/following::button[1]</value>
      <webElementGuid>7d17234b-8fb9-4231-b642-a2d8eaa1643e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Angsuran Per Bulan'])[1]/preceding::button[1]</value>
      <webElementGuid>7137e3d5-5f64-4abb-88a0-30af76b2ab7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rp 0'])[1]/preceding::button[1]</value>
      <webElementGuid>4a0542b1-1217-433e-9fda-3c7bc63745aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Hitung Simulasi']/parent::*</value>
      <webElementGuid>20f1ba27-261a-44b3-a4bb-c756956559ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/button</value>
      <webElementGuid>7cfc6301-a043-4190-a659-ec26920263b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'b5-btn_mobilbaru' and (text() = 'Hitung Simulasi' or . = 'Hitung Simulasi')]</value>
      <webElementGuid>a0e6c1ed-4816-483c-8a0e-83f3965ec66a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
