<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Harga OTR_b5-b12-Input_Mask_1</name>
   <tag></tag>
   <elementGuidId>3d1252e5-d60f-4596-8f4e-6883c38d051f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='b5-b12-Input_Mask']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b5-b12-Input_Mask</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>949d1ea0-118b-40ed-afbe-b91ed91a2e9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control OSFillParent masked-value</value>
      <webElementGuid>8611dfcb-5fd1-417e-8c96-d1a3d58b1d79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8bbbcf3c-43e5-4f10-bdc0-ee057d0a5dca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>16</value>
      <webElementGuid>1ffc0d0c-570b-44df-89ff-0fcbe7d70205</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>6208bb05-5db9-46b3-a7e7-918ed6eaef89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b5-b12-Input_Mask</value>
      <webElementGuid>5606d57c-e746-4173-8ac2-d166f3f63c55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>numeric</value>
      <webElementGuid>848b0667-3818-4c72-b2ec-4a8e6f9393fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b5-b12-Input_Mask&quot;)</value>
      <webElementGuid>3b1137ca-a92a-4773-9dea-20814e2df84b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='b5-b12-Input_Mask']</value>
      <webElementGuid>a17e6774-5910-4256-8319-78647e1573e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b5-b12-MaskedContent']/span/input</value>
      <webElementGuid>73e9247f-923e-48ca-82df-a66f9f40706b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div[2]/div/div/div/span/input</value>
      <webElementGuid>462769dd-6e65-4697-a460-4de0dd30b39b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'b5-b12-Input_Mask']</value>
      <webElementGuid>54e53785-7849-4193-91d0-6bcabf3e3a49</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
