<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Tenor_b5-TenorPeminjaman</name>
   <tag></tag>
   <elementGuidId>6386c0f7-84d1-4f47-a622-b3b73e2308b5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='b5-TenorPeminjaman']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b5-TenorPeminjaman</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>02217b89-c541-4b81-b262-dfeaae4e0b0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control OSFillParent</value>
      <webElementGuid>bad8e1a4-696f-4168-a3f1-d86aadf076be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>95e71e1b-c7cb-4edb-8f29-9e4ae0ec4ba0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>658aac25-e7b3-46f3-b189-84679383528e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>77990b16-7612-4fd6-9f91-3acf5c9b9113</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>60</value>
      <webElementGuid>05ffea55-4c18-4789-8e44-864377cc9c28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b5-TenorPeminjaman</value>
      <webElementGuid>60c07d40-6ee0-4e2a-b4ae-d6b3037f513a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b5-TenorPeminjaman&quot;)</value>
      <webElementGuid>b5dd3cbd-b826-4035-b1b8-bfda594f1747</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='b5-TenorPeminjaman']</value>
      <webElementGuid>f25225b3-ccc4-4a08-8332-46dd25b4b2b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b5-b14-Input']/span/input</value>
      <webElementGuid>52eada80-6d01-49ff-b423-fefec6a08908</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div/div[2]/span/input</value>
      <webElementGuid>55174272-1849-4a8d-b5e8-0bf89f88733d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'b5-TenorPeminjaman']</value>
      <webElementGuid>0ef9dab5-1db1-4de8-91ed-2905ffff1cee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
