<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_DAIHATSU</name>
   <tag></tag>
   <elementGuidId>97f4fc52-18b7-4c69-afab-3a9343eedbcd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='b5-l1-167_1-txt_namaarea']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b5-l1-167_1-txt_namaarea</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>032dba50-3094-46ed-bd46-5078a93fa10d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b5-l1-167_1-txt_namaarea</value>
      <webElementGuid>7c781729-c8a8-406c-bd2b-78b9e1484493</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>DAIHATSU</value>
      <webElementGuid>2ab6d632-0817-463e-bc82-dd69b89029b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b5-l1-167_1-txt_namaarea&quot;)</value>
      <webElementGuid>ac0925fa-7ed3-4fd0-a069-59170afb7334</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='b5-l1-167_1-txt_namaarea']</value>
      <webElementGuid>856f2f24-40ea-4749-80c1-31a188c1b9cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b5-ListGroupArea']/div[2]/span</value>
      <webElementGuid>20e2c184-0977-4560-a1f9-adcce4556f0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TOYOTA'])[1]/following::span[1]</value>
      <webElementGuid>f1e7d93c-bc1b-49b1-825c-aaa96a9e74a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Harus dipilih!'])[1]/following::span[2]</value>
      <webElementGuid>e448e51f-ef49-4c67-9a45-303b404e0ae9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ISUZU'])[1]/preceding::span[1]</value>
      <webElementGuid>e2083389-5a46-4ff6-9558-0884c52b24f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BMW'])[1]/preceding::span[2]</value>
      <webElementGuid>6255febf-8c65-4eff-89f4-b34c6a4a2602</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='DAIHATSU']/parent::*</value>
      <webElementGuid>192aed42-5f34-4e1f-a055-31d4b44d7064</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div[2]/span</value>
      <webElementGuid>c56597d0-767c-410d-9390-f7c77bd87f9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'b5-l1-167_1-txt_namaarea' and (text() = 'DAIHATSU' or . = 'DAIHATSU')]</value>
      <webElementGuid>4c1606bb-cc94-43ef-a0ad-a9d98dbd18f2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
