<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_2022</name>
   <tag></tag>
   <elementGuidId>7c70d615-5bfc-41f4-8f52-1965ea606c92</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='b5-l4-177_0-txt_namaarea2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b5-l4-177_0-txt_namaarea2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>cfd63b9a-fe00-44a3-8188-ca74d140e3c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b5-l4-177_0-txt_namaarea2</value>
      <webElementGuid>62f4657f-4021-4d7b-946b-845362bd0f14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>2022</value>
      <webElementGuid>75a6cb8d-7f2a-4b89-a6bf-99acea08cd37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b5-l4-177_0-txt_namaarea2&quot;)</value>
      <webElementGuid>15155875-b4de-4bbb-b18c-cfc2fb45cd06</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='b5-l4-177_0-txt_namaarea2']</value>
      <webElementGuid>18d019cf-8e1c-43b1-bc37-7d94c86f8969</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b5-ListGroupTahun']/div/span</value>
      <webElementGuid>af4dd103-f222-495c-afd9-5a4244a4149f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tahun'])[1]/following::span[2]</value>
      <webElementGuid>98df568a-f2c6-40d7-b313-77c4477ef4e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Model'])[1]/following::span[4]</value>
      <webElementGuid>d50dc156-abfc-4bdf-bbfc-2d75d3b690cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Harus dipilih'])[1]/preceding::span[2]</value>
      <webElementGuid>4ba903b5-798e-4ec6-b352-40de7b9aefd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Harga OTR'])[1]/preceding::span[3]</value>
      <webElementGuid>6d82240f-4971-4284-a3ed-9c8a8eaf68a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='2022']/parent::*</value>
      <webElementGuid>719aa0f4-7620-447f-aaf2-d5e7d647eed6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div/span</value>
      <webElementGuid>5403a12d-144c-4a52-8c66-20b5a2d79c82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'b5-l4-177_0-txt_namaarea2' and (text() = '2022' or . = '2022')]</value>
      <webElementGuid>5cfda5d9-41aa-414a-b14d-509ddadfebff</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
