<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_DKI Jakarta dan Banten</name>
   <tag></tag>
   <elementGuidId>6d234b17-8b3b-4d30-9ace-52b7ee1b4951</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='b5-l7-170_6-txt_namaarea3']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b5-l7-170_6-txt_namaarea3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>e593176c-6080-4852-a566-8cf3a40fcb50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b5-l7-170_6-txt_namaarea3</value>
      <webElementGuid>fb6db71c-f05d-4349-a641-41791ad9e3de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>DKI Jakarta dan Banten</value>
      <webElementGuid>105ac53c-7d5d-4cfb-8974-dcfbaea95d2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b5-l7-170_6-txt_namaarea3&quot;)</value>
      <webElementGuid>4c3aace4-6113-4edb-85db-e8be10eee5ee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='b5-l7-170_6-txt_namaarea3']</value>
      <webElementGuid>3dda7acc-bf90-453a-b58d-a330b00905e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b5-ListGroupArea2']/div/span</value>
      <webElementGuid>455803f2-a26a-438a-8117-e20072578d5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Area Pengajuan'])[1]/following::span[2]</value>
      <webElementGuid>2db96faa-b1ac-4a52-9f92-064c559aec91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tenor'])[1]/following::span[3]</value>
      <webElementGuid>fc5dd00a-c661-4044-83cf-4eb64ded4b93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pilih Semua Rekomendasi Asuransi'])[1]/preceding::span[1]</value>
      <webElementGuid>5c42ce8b-9955-4e80-80af-1a51f21f659b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lihat detail asuransi'])[1]/preceding::span[3]</value>
      <webElementGuid>92f15418-5653-49cf-ae0d-fe3f2534a62f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='DKI Jakarta dan Banten']/parent::*</value>
      <webElementGuid>38c95206-ca53-47ff-8db2-a8785dcdf706</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/span</value>
      <webElementGuid>f062245f-c8ec-420c-bdc8-96642032ca61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'b5-l7-170_6-txt_namaarea3' and (text() = 'DKI Jakarta dan Banten' or . = 'DKI Jakarta dan Banten')]</value>
      <webElementGuid>9b83c429-97fe-4d55-9a85-4daf93e8ee85</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
