<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Kalkulator Kredit</name>
   <tag></tag>
   <elementGuidId>9307ce5d-029b-47e8-9994-e3347b33c080</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b4-MenuSimulasi']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.menu-header-item.text-menu</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>5ba3c1f1-ca91-4042-b17a-7daab6c72bee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>menu-header-item text-menu</value>
      <webElementGuid>2dfda02e-3188-4295-85ae-bde769a021f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/accone/SimulasiKredit?ActiveTab=0&amp;DataSimulasi=&amp;FromBack=false</value>
      <webElementGuid>639f71bb-9c4e-4ced-a536-ef5ac2b577fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Kalkulator Kredit</value>
      <webElementGuid>4277f372-cb31-49f5-b658-df0bc5788818</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b4-MenuSimulasi&quot;)/a[@class=&quot;menu-header-item text-menu&quot;]</value>
      <webElementGuid>3c6a5ea8-c0c3-450f-9b73-e2245d522b91</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b4-MenuSimulasi']/a</value>
      <webElementGuid>9d5fc8bc-a40e-4159-8132-f279a292a7ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Kalkulator Kredit')]</value>
      <webElementGuid>44770b2c-1f67-411f-8076-dccfe2775c5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pengkinian Data'])[1]/following::a[1]</value>
      <webElementGuid>517ab119-b88e-4d66-9ba5-7295ca7bb202</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Layanan Mandiri'])[1]/following::a[2]</value>
      <webElementGuid>befa0078-e4f5-4786-907e-fc8c54f239ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login'])[2]/preceding::a[1]</value>
      <webElementGuid>fb69e3e2-6a29-400a-a5d5-230714616f32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email atau Nomor Handphone'])[1]/preceding::a[2]</value>
      <webElementGuid>fdab477d-57e4-4a13-bf63-dea93b34ba99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Kalkulator Kredit']/parent::*</value>
      <webElementGuid>67d3279c-e960-4776-b5d4-72c6bf0d3b4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/accone/SimulasiKredit?ActiveTab=0&amp;DataSimulasi=&amp;FromBack=false')]</value>
      <webElementGuid>1ecf4226-f78c-480e-b9b5-44296586cd83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/a</value>
      <webElementGuid>15043d09-a5db-4f33-911c-d2342461b007</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/accone/SimulasiKredit?ActiveTab=0&amp;DataSimulasi=&amp;FromBack=false' and (text() = 'Kalkulator Kredit' or . = 'Kalkulator Kredit')]</value>
      <webElementGuid>c5c04f14-8986-4bef-aed1-1f5fd05b6440</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
