<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input - Konfirmasi Kata Sandi</name>
   <tag></tag>
   <elementGuidId>f625e8c9-f4f5-4df8-8dca-82afd14483d2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='b5-Input_KonfirmSandi']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b5-Input_KonfirmSandi</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>866ca4d7-a26a-459c-a16b-47198f4bc9ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control OSFillParent</value>
      <webElementGuid>91193997-a013-46cc-90f3-757393b6daf3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>07ab8bf1-234e-4c3e-93a9-f70e467927ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>0f273138-bfc0-4a70-9787-c462218089dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1234567f</value>
      <webElementGuid>d53cabfe-6c09-48f1-b137-0e17c6c922ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b5-Input_KonfirmSandi</value>
      <webElementGuid>79e3563b-434c-4cf0-8bce-9e9a173c58e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b5-Input_KonfirmSandi&quot;)</value>
      <webElementGuid>03e76bcd-0519-4e82-8194-c6b0b7a0771a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='b5-Input_KonfirmSandi']</value>
      <webElementGuid>b1ddbe1f-5b8d-40c8-9d34-2b59b87542bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b5-InputKonfirmKataSandi']/span/input</value>
      <webElementGuid>f46f040b-4792-4f43-aa24-94fcf612159f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div/div[2]/div/div/div[2]/div/span/input</value>
      <webElementGuid>d717c096-0d51-4cb2-b205-3a83a852498e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'b5-Input_KonfirmSandi']</value>
      <webElementGuid>9b6e2287-e782-414f-af2b-8dfaf4a0e99f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
