<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>RadioButton - Laki-laki</name>
   <tag></tag>
   <elementGuidId>5bba7989-b133-4842-9823-2a6b61c14f52</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='b5-RadioButton1-input']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b5-RadioButton1-input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>82caa91c-a2d3-43e7-8bdb-670fad405dbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>9c83d2cc-f787-4994-9c3a-dca337021ec0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b5-RadioButton1-input</value>
      <webElementGuid>3c803658-1086-4a0a-8eb9-eb007097bd48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>radio-button</value>
      <webElementGuid>9600db6e-a001-4826-8bd1-3e5f9531f671</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>b5-RadioGroup1</value>
      <webElementGuid>a9f56aa9-2b07-4ab5-986d-8a7966ea28b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>M</value>
      <webElementGuid>a7f77099-e038-4e5e-8053-a56cbd6ded0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b5-RadioButton1-input&quot;)</value>
      <webElementGuid>448a62f6-426a-418f-b147-321fba5170b6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='b5-RadioButton1-input']</value>
      <webElementGuid>f45bc451-9cfd-4a8e-a60a-6568e70730bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b5-RadioButton1']/input</value>
      <webElementGuid>cf4ab272-dec6-48f7-84bc-bacf515ff23c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>ce00bf3e-085a-4992-a8d1-175c57033283</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'b5-RadioButton1-input' and @name = 'b5-RadioGroup1']</value>
      <webElementGuid>1c2ee698-973b-4113-be38-443f8c2de87e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
