<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Download Tokopedia App</name>
   <tag></tag>
   <elementGuidId>a4c6ac4c-fa9c-40af-9797-50eaacd2ccfa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='header-main-wrapper']/div/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.css-7k41it</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>8bec1529-7723-405a-97ea-df5476d8d7d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/mobile-apps/</value>
      <webElementGuid>a247afa6-6753-4a04-bb3b-cc13ee63a205</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>19e841e3-f7de-44d0-ad01-f0f0addd7ab5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rel</name>
      <type>Main</type>
      <value>noopener noreferrer</value>
      <webElementGuid>5c16d0e1-43f4-42a1-9904-e35dbffb512a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-7k41it</value>
      <webElementGuid>f7b38600-0a88-41ec-a734-62f933a8e83c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Download Tokopedia App</value>
      <webElementGuid>37c702d0-2a75-4079-9b12-70e090e4aacc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header-main-wrapper&quot;)/div[@class=&quot;css-1jzqg4i edxse4c2&quot;]/div[@class=&quot;css-1t2cza5&quot;]/a[@class=&quot;css-7k41it&quot;]</value>
      <webElementGuid>52686b57-cdc1-49df-940d-6cf0017472cd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='header-main-wrapper']/div/div/a</value>
      <webElementGuid>84b268f9-f17d-4c50-a2a7-07ad99840aa7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tentang Tokopedia'])[1]/preceding::a[1]</value>
      <webElementGuid>f51f269b-fb7e-4172-a497-d673579d517a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mitra Tokopedia'])[1]/preceding::a[2]</value>
      <webElementGuid>b8f19df0-f7c8-4172-98ef-2149395a5e0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Download Tokopedia App']/parent::*</value>
      <webElementGuid>ba8b6f83-1d7e-4326-9f3e-bec6a1622483</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/mobile-apps/')]</value>
      <webElementGuid>152c6857-667e-4516-8c31-9a4e6387ca17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a</value>
      <webElementGuid>7df2f919-3752-4a2f-8b9b-53f1f7585b2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/mobile-apps/' and (text() = ' Download Tokopedia App' or . = ' Download Tokopedia App')]</value>
      <webElementGuid>cc82fca9-462f-4d1e-8a39-68b0bab61171</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
