<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img - Playstore</name>
   <tag></tag>
   <elementGuidId>08134e5e-09b8-4196-8b4e-03db82e6a90b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='header-main-wrapper']/div[2]/div/div[2]/div/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;playstoreimage&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>19bf05a6-0482-4cc5-ac91-6148cdde9f6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://assets.tokopedia.net/assets-tokopedia-lite/v2/zeus/kratos/e25ec508.svg</value>
      <webElementGuid>04bf4bdc-0e44-47be-8b3c-ce018be63154</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>112px</value>
      <webElementGuid>0a0dc68b-68fc-439f-906c-319fe61aba7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>33px</value>
      <webElementGuid>eae385f7-f78d-4e88-8c7b-d8510a68ed0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>playstoreimage</value>
      <webElementGuid>782d532f-4e78-4df8-a129-0cf9ed5dc7e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header-main-wrapper&quot;)/div[@class=&quot;css-o503hg&quot;]/div[@class=&quot;css-1h31drq&quot;]/div[@class=&quot;css-12bpv28&quot;]/div[1]/a[1]/img[1]</value>
      <webElementGuid>7a67eda2-2b53-42a4-89b7-bf040fef3838</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='header-main-wrapper']/div[2]/div/div[2]/div/a/img</value>
      <webElementGuid>6408747c-2180-4c73-aff3-762695e245bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='playstoreimage']</value>
      <webElementGuid>912b2590-a122-4656-af6f-74f131ecb15a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/img</value>
      <webElementGuid>bff6bf66-b31e-412c-bfe2-74bcaf576201</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://assets.tokopedia.net/assets-tokopedia-lite/v2/zeus/kratos/e25ec508.svg' and @alt = 'playstoreimage']</value>
      <webElementGuid>cc0562b5-d0e6-4e8c-bf39-dd7676a4baf2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
