<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Format email yang dimasukkan belum sesuai, Contoh  biko.maryonogmail.com</name>
   <tag></tag>
   <elementGuidId>cc6fb39d-8b13-4bfe-87a2-fc114e990b14</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b5-b1-Input']/span/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.validation-message</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>9280d73a-e3bc-4809-99df-c6105ab8c53c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>validation-message</value>
      <webElementGuid>41b600f6-06f2-47da-bb4b-eee49e5f13fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Format email yang dimasukkan belum sesuai, Contoh : biko.maryono@gmail.com</value>
      <webElementGuid>89bf233c-b6e9-4ba9-a185-31f72c0858a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b5-b1-Input&quot;)/span[@class=&quot;input-text&quot;]/span[@class=&quot;validation-message&quot;]</value>
      <webElementGuid>23d156d8-8649-4b43-a067-0e29ead495ce</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b5-b1-Input']/span/span</value>
      <webElementGuid>95bb6756-64e1-4d66-b44f-8e6433e63e97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email atau Nomor Handphone'])[2]/following::span[2]</value>
      <webElementGuid>a65ad869-071b-43ce-89e7-dc26a473b63a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Masuk ke Akun Anda'])[1]/following::span[3]</value>
      <webElementGuid>11278e50-1069-4310-b56d-e56c32d0102b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kata Sandi'])[2]/preceding::span[1]</value>
      <webElementGuid>60eec8e0-3eba-4382-a33c-25dd0430fe5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lupa Kata Sandi?'])[2]/preceding::span[3]</value>
      <webElementGuid>675fd4ad-83ea-49db-bc76-6785f2c3454e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Format email yang dimasukkan belum sesuai, Contoh : biko.maryono@gmail.com']/parent::*</value>
      <webElementGuid>f4286413-8c19-4973-b5cb-3f80ff7f1fe5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span</value>
      <webElementGuid>f82ec81a-0c0b-4fc1-89d6-93869f9a72cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Format email yang dimasukkan belum sesuai, Contoh : biko.maryono@gmail.com' or . = 'Format email yang dimasukkan belum sesuai, Contoh : biko.maryono@gmail.com')]</value>
      <webElementGuid>e2fbda16-e04d-4b53-b0e7-2c9eab89d044</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
