<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Kata Sandi minimal 7 Karakter</name>
   <tag></tag>
   <elementGuidId>fc5a6700-647b-4469-8be6-c52d20815166</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b5-InputKataSandi3']/span/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.validation-message</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>4a763c9a-a04f-41d6-ab22-46081700056e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>validation-message</value>
      <webElementGuid>f04e18d7-1223-4738-a3cc-f6ec805ae9af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Kata Sandi minimal 7 Karakter</value>
      <webElementGuid>81fcc18d-f21b-4c5d-bd17-5d817c84eefc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b5-InputKataSandi3&quot;)/span[@class=&quot;input-password&quot;]/span[@class=&quot;validation-message&quot;]</value>
      <webElementGuid>cc24d8a3-5777-40f5-af05-0bb761c43580</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>2a46b142-2abe-4fc2-ac69-12fadaf47e68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>validation-message</value>
      <webElementGuid>e898fc90-7f78-4052-8021-127a19956c4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Kata Sandi minimal 7 Karakter</value>
      <webElementGuid>5ee28ea8-32c2-4ade-9822-abbc4c95fce4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b5-InputKataSandi3&quot;)/span[@class=&quot;input-password&quot;]/span[@class=&quot;validation-message&quot;]</value>
      <webElementGuid>4774fdd9-67d3-4354-896e-e708d0a8d984</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b5-InputKataSandi3']/span/span</value>
      <webElementGuid>b8da2d30-b123-465b-b991-da1b12089dd6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kata Sandi'])[2]/following::span[2]</value>
      <webElementGuid>4ed9c0c7-b8b9-4a71-a885-862d4e9d438a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email atau Nomor Handphone'])[2]/following::span[4]</value>
      <webElementGuid>7eec9297-0054-49f9-befa-9d84e9b683b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lupa Kata Sandi?'])[2]/preceding::span[1]</value>
      <webElementGuid>47f54771-0025-4cde-919c-ae691dbbe9bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Masuk'])[2]/preceding::span[2]</value>
      <webElementGuid>b8837eae-ae25-4658-8700-1c4dd00e81d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Kata Sandi minimal 7 Karakter']/parent::*</value>
      <webElementGuid>8a66eb52-8815-4d92-8250-3ce52fbb3398</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span</value>
      <webElementGuid>5ca99394-1eda-4e03-951d-01370b68fe9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Kata Sandi minimal 7 Karakter' or . = 'Kata Sandi minimal 7 Karakter')]</value>
      <webElementGuid>bbedb613-e0fc-45fa-a94e-ac7fe6f49cdf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
