<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input - Hitung Simulasi</name>
   <tag></tag>
   <elementGuidId>b2e3692a-7fda-4eb7-bd5f-cb60dcf6dc21</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b5-b6-Column1']/div/div/div[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.padding-top-xl</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>0a49b019-2eee-4810-97e6-8ffc8a7ca170</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>padding-top-xl</value>
      <webElementGuid>16a62ed9-cb50-40a3-bdb9-fde1ded32089</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Hitung Simulasi</value>
      <webElementGuid>ffab92a3-e683-45b7-8979-29fc41d5cf79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b5-b6-Column1&quot;)/div[@class=&quot;flex-justify-center full-height&quot;]/div[@class=&quot;padding-l font-size-p OSInline&quot;]/div[@class=&quot;padding-top-xl&quot;]</value>
      <webElementGuid>6e598979-f24d-4c8c-852c-690c665e47c0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b5-b6-Column1']/div/div/div[3]</value>
      <webElementGuid>536f6693-0247-4396-9c7d-0892a3aeb2a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lihat detail asuransi'])[1]/following::div[1]</value>
      <webElementGuid>5954f505-7193-42a6-a3e8-caa7ef856dda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pilih Semua Rekomendasi Asuransi'])[1]/following::div[3]</value>
      <webElementGuid>c6693eeb-c71e-48e4-9406-ecbb06079936</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Angsuran Per Bulan'])[1]/preceding::div[1]</value>
      <webElementGuid>67f7ab22-f0c1-4e06-a73e-d9350a9695fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div/div/div/div/div/div/div/div/div[3]</value>
      <webElementGuid>a1e4d99d-da7d-4304-88fa-274f7589c25a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Hitung Simulasi' or . = 'Hitung Simulasi')]</value>
      <webElementGuid>4032fb2c-f90c-46be-82ce-30b663201bcb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
