<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Promo</name>
   <tag></tag>
   <elementGuidId>3a46472d-9db9-455d-80d3-c23207214a73</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='header-main-wrapper']/div/div[2]/a[4]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>fcd6715d-95a7-4264-9516-5329f16b430f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/promo/</value>
      <webElementGuid>c106edda-e31e-464a-a977-a440cfcd8950</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-f0xez1</value>
      <webElementGuid>8fb1f216-a7cb-43c3-af5a-0ccc0530ece3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>107ea879-60ea-4568-8f68-daeaa498a427</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rel</name>
      <type>Main</type>
      <value>noopener noreferrer</value>
      <webElementGuid>20535fc7-5e97-46f0-9714-42fbee1ce074</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>btnHeaderPromo</value>
      <webElementGuid>fb209390-3df2-4d58-ab8d-5f1c8294d0f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Promo</value>
      <webElementGuid>3431ef5c-94c1-4088-b976-63750be04702</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header-main-wrapper&quot;)/div[@class=&quot;css-1jzqg4i edxse4c2&quot;]/div[@class=&quot;css-1dm32rh edxse4c4&quot;]/a[@class=&quot;css-f0xez1&quot;]</value>
      <webElementGuid>7cd1b700-c833-40a0-a9ea-800ab8ca268c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='header-main-wrapper']/div/div[2]/a[4]</value>
      <webElementGuid>30686f7e-5004-4a75-81ef-29e091ead3f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Promo')]</value>
      <webElementGuid>72d3e636-61d5-4a1c-8991-8f9146967c18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mulai Berjualan'])[1]/following::a[1]</value>
      <webElementGuid>98c1b1b4-e3ab-49dc-a76f-c0df8486730f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mitra Tokopedia'])[1]/following::a[2]</value>
      <webElementGuid>3e4b4133-3c67-48e4-b1e2-f9b3013ea045</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tokopedia Care'])[1]/preceding::a[1]</value>
      <webElementGuid>d297c03e-e6df-402e-84a5-413d025e4024</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kategori'])[1]/preceding::a[3]</value>
      <webElementGuid>4e271a08-9f50-4e61-bd5c-45a101401a63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Promo']/parent::*</value>
      <webElementGuid>946cb2db-42ff-44b8-b64c-854813b03fad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/promo/')]</value>
      <webElementGuid>aa6a25d3-f6ef-431a-b708-84213896bae7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[4]</value>
      <webElementGuid>aa030e02-a211-46e2-97d2-70f719852521</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/promo/' and (text() = 'Promo' or . = 'Promo')]</value>
      <webElementGuid>5d987ea6-5d91-4dac-9287-9de5ad365f0a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
