<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Login_terms</name>
   <tag></tag>
   <elementGuidId>0a3fe266-7671-4f4a-979b-57692a47bd6d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@name='terms'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#tab-content2 > form[name=&quot;register&quot;] > div.btn > input[name=&quot;terms&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5208e0cd-a7b5-4d7a-b132-541077c76f65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>07c55fec-2abd-4579-bf50-e53b2880d8ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>terms</value>
      <webElementGuid>5dd377de-5105-4b52-8e49-b16019977817</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tab-content2&quot;)/form[1]/div[@class=&quot;btn&quot;]/input[1]</value>
      <webElementGuid>4fdff3c3-b5b2-453b-8aec-775a6638af3f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name='terms'])[2]</value>
      <webElementGuid>bccebabb-17fe-4674-bc90-93ff23004eaa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab-content2']/form/div/input</value>
      <webElementGuid>09406497-5e94-4835-912b-b7f3d7fe3b9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div/form/div/input</value>
      <webElementGuid>9330b856-42df-4b82-81a7-b761374a7b1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'terms']</value>
      <webElementGuid>af4a0417-3b58-4ce3-bc54-73333edce13b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
