<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Iklan_Promosi</name>
   <tag></tag>
   <elementGuidId>5df9e60b-aa7e-4634-b1f0-8af281c033d7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='zeus-root']/div/div[2]/div/div[2]/div[3]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.css-gz15zn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>33feab2b-5d41-4052-93a2-4c259e24cd31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-gz15zn</value>
      <webElementGuid>4dbbaba4-4a7b-4a83-b4a3-53359442bc82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Dipromosikan olehPromosi oleh Topads berdasarkan minatmuBaca SelengkapnyaPaulmayCashback Rp10000Belanja di Paulmay, diskon hingga 50%! Yuk Beli Sekarang!Cek Sekarang</value>
      <webElementGuid>0c41c6a8-f7b5-42ec-b774-c70fb40414ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;zeus-root&quot;)/div[@class=&quot;css-3lpl5n&quot;]/div[@class=&quot;css-jau1bt&quot;]/div[@class=&quot;css-1c82svt&quot;]/div[@class=&quot;css-rjanld&quot;]/div[@class=&quot;css-1c822ma&quot;]/div[@class=&quot;css-gz15zn&quot;]</value>
      <webElementGuid>f6e1fa74-8670-4ec7-8349-a58216cdf462</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='zeus-root']/div/div[2]/div/div[2]/div[3]/div</value>
      <webElementGuid>c3091fa9-9e75-4620-b00f-26d5a856bcc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Harga Terendah'])[1]/following::div[2]</value>
      <webElementGuid>da811653-f3de-4f10-8d29-7fd4db3e6854</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Harga Tertinggi'])[1]/following::div[2]</value>
      <webElementGuid>2cf0ee4c-1593-4021-85d5-1ee83486a334</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div[3]/div</value>
      <webElementGuid>471a6a5f-0b2f-4561-8d11-b64158cbb6c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Dipromosikan olehPromosi oleh Topads berdasarkan minatmuBaca SelengkapnyaPaulmayCashback Rp10000Belanja di Paulmay, diskon hingga 50%! Yuk Beli Sekarang!Cek Sekarang' or . = 'Dipromosikan olehPromosi oleh Topads berdasarkan minatmuBaca SelengkapnyaPaulmayCashback Rp10000Belanja di Paulmay, diskon hingga 50%! Yuk Beli Sekarang!Cek Sekarang')]</value>
      <webElementGuid>9185aaff-8d06-4525-9bd2-c8ec78b5cdbd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
