<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_60</name>
   <tag></tag>
   <elementGuidId>76e739e8-2d3a-4792-a5d0-9efd93bf4f6d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b5-ListGroupArea5']/div[5]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>2793b8ee-4dbe-48cc-be37-8729571d2d16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>list-item</value>
      <webElementGuid>5e048566-04a4-44ea-8761-4d0c31112517</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>60</value>
      <webElementGuid>b1ff0df9-ad33-4852-91d5-7db1294fc41d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b5-ListGroupArea5&quot;)/div[@class=&quot;list-item&quot;]</value>
      <webElementGuid>f57a582b-aa1c-4fa1-ba6a-47d6ce11bfde</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b5-ListGroupArea5']/div[5]</value>
      <webElementGuid>7e83a4ee-ab40-4908-8fa0-e099e0f61372</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tenor'])[1]/following::div[9]</value>
      <webElementGuid>c271d521-915f-4137-941e-ec2ae234796b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DP(%)'])[1]/following::div[15]</value>
      <webElementGuid>74968f1c-a25f-4954-a69a-13ad1508bb67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Area Pengajuan'])[1]/preceding::div[1]</value>
      <webElementGuid>aa941215-34b6-422f-995e-36a8babdfb64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pilih Semua Rekomendasi Asuransi'])[1]/preceding::div[7]</value>
      <webElementGuid>d8a7c906-2f54-4510-bfde-04fac9591849</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div/div[2]/div[2]/div/div[5]</value>
      <webElementGuid>d442c774-9c57-4ee7-8aff-366aa4b38216</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '60' or . = '60')]</value>
      <webElementGuid>d33fb199-b5cc-4dc7-8cec-13bfb1970602</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
