<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_For You</name>
   <tag></tag>
   <elementGuidId>5a8acb46-7b64-4bce-939d-58e0b19223b9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='zeus-root']/div/main/section[3]/div/div/div/div/div/div/div/div/button/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.active.css-825sy5.e1ugnrpg0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>37057b8e-d632-4c5b-9c12-0ea23c8dade3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>active css-825sy5 e1ugnrpg0</value>
      <webElementGuid>b26501f5-c749-4834-820a-10e040b2a476</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>divMegaTabText</value>
      <webElementGuid>cc1e7d36-3e9d-458c-b192-85565e316538</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>For You</value>
      <webElementGuid>6beb9ab1-b784-4f0d-a26a-9f870bc6ee9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;zeus-root&quot;)/div[@class=&quot;css-3lpl5n&quot;]/main[@class=&quot;css-1rhxxyn&quot;]/section[@class=&quot;css-1jllmtg&quot;]/div[@class=&quot;css-wkhbw8&quot;]/div[@class=&quot;css-10xau59&quot;]/div[@class=&quot;css-6bc98m&quot;]/div[@class=&quot;css-1u5y540&quot;]/div[@class=&quot;css-1mwbycl sticky&quot;]/div[@class=&quot;css-9o0z3u sticky&quot;]/div[@class=&quot;css-g2vnn6&quot;]/div[@class=&quot;css-mdfmy2&quot;]/button[@class=&quot;css-4poblp&quot;]/div[@class=&quot;active css-825sy5 e1ugnrpg0&quot;]</value>
      <webElementGuid>c9530af8-eaa3-4a31-a177-96f9b49302d0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='zeus-root']/div/main/section[3]/div/div/div/div/div/div/div/div/button/div</value>
      <webElementGuid>bc1ff831-54c3-4f73-8791-75d376c2f489</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='next'])[7]/following::div[15]</value>
      <webElementGuid>368c2b83-1912-448a-b989-32e71269b238</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='prev'])[7]/following::div[16]</value>
      <webElementGuid>b49cfb9b-9b76-4628-b4f6-c8277eaa98be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Festival Distro Lokal'])[1]/preceding::div[1]</value>
      <webElementGuid>14b7d89b-433b-4e1e-9cf5-c2ef17d5e0c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Special Discount'])[1]/preceding::div[2]</value>
      <webElementGuid>d56ffc86-2c7e-4c2c-9d91-b63fbb42c903</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='For You']/parent::*</value>
      <webElementGuid>b5d55dd8-4655-437b-abd4-3dca6982d49b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/div</value>
      <webElementGuid>5aa89973-30e2-457a-910f-ceb064e33a2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'For You' or . = 'For You')]</value>
      <webElementGuid>1c1abc62-fbed-45d0-a69e-8b2b4381d206</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
