<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_Bayar di tempat  49rb</name>
   <tag></tag>
   <elementGuidId>fb2be255-df1e-408a-908d-bcbc2b127a25</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='zeus-root']/div/main/section[2]/div[4]/section/div/div/h2</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>section.css-15w4gyx-unf-card.eeeacht0 > div.css-x2jffe > div.css-qu5ty6 > h2.css-t5es2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>ceb3fdc6-5ceb-423d-b50a-049ff90f318e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-t5es2</value>
      <webElementGuid>fbc8e219-c2b1-4c53-b68d-261abbfeefeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>lblHomeCarouselTitle</value>
      <webElementGuid>a2676661-3348-4f15-b42b-11b40cb01c91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Bayar di tempat &lt; 49rb</value>
      <webElementGuid>5fe6aafc-c7a9-4203-94a9-d244a6c68426</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;zeus-root&quot;)/div[@class=&quot;css-3lpl5n&quot;]/main[@class=&quot;css-1rhxxyn&quot;]/section[@class=&quot;css-1jllmtg&quot;]/div[@class=&quot;css-183zhx4&quot;]/section[@class=&quot;css-15w4gyx-unf-card eeeacht0&quot;]/div[@class=&quot;css-x2jffe&quot;]/div[@class=&quot;css-qu5ty6&quot;]/h2[@class=&quot;css-t5es2&quot;]</value>
      <webElementGuid>4badd91a-9b55-4802-b814-7379070d952d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='zeus-root']/div/main/section[2]/div[4]/section/div/div/h2</value>
      <webElementGuid>5d12b927-5448-48df-8371-aea06dd1f2ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='next'])[5]/following::h2[1]</value>
      <webElementGuid>35431e64-6381-4ae2-b171-f34e31551a1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='prev'])[5]/following::h2[1]</value>
      <webElementGuid>98c31bce-88f7-47dd-bd04-4b026e5f2e01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sportacular'])[1]/preceding::h2[1]</value>
      <webElementGuid>16a69016-cbb5-44fb-8a92-feae1379bf1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='LIGER Handsfree headset earphone L-10 METAL stereo &amp; bass'])[1]/preceding::h2[1]</value>
      <webElementGuid>e65b73f0-f1a5-4587-ba30-74bfa9fe31f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Bayar di tempat &lt; 49rb']/parent::*</value>
      <webElementGuid>afec498c-217b-4bcd-89e3-153164a1d227</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/section/div/div/h2</value>
      <webElementGuid>4b438fe7-42dd-45b2-9306-2b973e6e6eea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[(text() = 'Bayar di tempat &lt; 49rb' or . = 'Bayar di tempat &lt; 49rb')]</value>
      <webElementGuid>ca5ba6af-0e8a-4833-87bd-39d01ff008a3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
