<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Select City pd Jogja</name>
   <tag></tag>
   <elementGuidId>8408c1f7-d11e-4030-9aa9-3a5998ae3a2f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cityId']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cityId</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>a421ccd6-528d-4857-b5fd-81bb48516dbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>city</value>
      <webElementGuid>5ff4caf2-2307-477e-9355-f825e221cead</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>last cities</value>
      <webElementGuid>b0b54398-4889-4164-bc9f-e94a37d45579</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cityId</value>
      <webElementGuid>b9382ef4-40df-4983-b1ae-fcd2ee5e4888</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
   Select City
BambanglipuroBanguntapanBantulDepokGampingGodeanJetisKasihanNgaglikPandakPundongSewonSeyeganSlemanSrandakanWonosariYogyakarta</value>
      <webElementGuid>97d254f0-988b-415a-a9c6-f6b2ca46ddc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cityId&quot;)</value>
      <webElementGuid>fc77bcb6-6c70-4304-af17-15798efb9233</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cityId']</value>
      <webElementGuid>b185e3f0-789b-4bb2-81e4-db11be2c7240</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab-content1']/form/select[4]</value>
      <webElementGuid>cb8eb5bf-c769-453e-91b5-c12a3137ebcf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Register'])[1]/following::select[4]</value>
      <webElementGuid>2ca9fcdd-ceff-4566-b123-3ce32c70a726</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login'])[1]/preceding::select[1]</value>
      <webElementGuid>28cd7f9e-8033-4034-9541-d2f68960b618</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select[4]</value>
      <webElementGuid>54aea8bc-0378-4cd3-aa64-55c418121b6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'city' and @id = 'cityId' and (text() = '
   Select City
BambanglipuroBanguntapanBantulDepokGampingGodeanJetisKasihanNgaglikPandakPundongSewonSeyeganSlemanSrandakanWonosariYogyakarta' or . = '
   Select City
BambanglipuroBanguntapanBantulDepokGampingGodeanJetisKasihanNgaglikPandakPundongSewonSeyeganSlemanSrandakanWonosariYogyakarta')]</value>
      <webElementGuid>282b388d-1be5-43f0-b2d6-8972352e64ba</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
