<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_1</name>
   <tag></tag>
   <elementGuidId>66468e63-9bf0-4447-a573-3ffddeb40716</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.container > img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[2]/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>94a6cfc9-9169-4e87-8cb5-5934463c3720</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>img/Profile.jpg</value>
      <webElementGuid>e8486d79-f254-472a-b993-ac5140ebb758</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;container&quot;]/img[1]</value>
      <webElementGuid>94c6cf21-7acb-4b51-be68-94ae3812d212</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/img</value>
      <webElementGuid>582dd0da-dd1c-4858-9136-bec18c03d2bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'img/Profile.jpg']</value>
      <webElementGuid>8251690f-cb88-47e6-a866-bf3076d2de1e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
