<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div - Bar Tokopedia</name>
   <tag></tag>
   <elementGuidId>6e783192-a538-48f2-974e-adcaf6875a4e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='header-main-wrapper']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#header-main-wrapper</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>dcb3b8e1-4cf5-4a62-8e64-e2279227e2bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>header-main-wrapper</value>
      <webElementGuid>571d367e-a720-4c96-8e9f-4cb9fff51fc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-19rqlec edxse4c0</value>
      <webElementGuid>01c7338e-a9a4-4d7e-b3ea-c927557e958b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Download Tokopedia AppTentang TokopediaMitra TokopediaMulai Berjualan PromoTokopedia CareKategori  Masuk Daftar redmi note 10shampers lebaranmeja tviphone xriphone 13android tv boxDikirim keJakarta Pusat</value>
      <webElementGuid>171d2cc6-4e8d-407a-849f-40fe2791d3e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header-main-wrapper&quot;)</value>
      <webElementGuid>20a813f1-93a8-4f9b-beea-5a878cf9b5fe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='header-main-wrapper']</value>
      <webElementGuid>d8300a18-a43b-4193-b66a-d68ff0f403cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='zeus-header']/div/div</value>
      <webElementGuid>b9d0e61e-d86f-41ee-be62-afe1c29ffdc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div</value>
      <webElementGuid>feb9a42c-7bec-4c8c-85c8-30c213a44559</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'header-main-wrapper' and (text() = ' Download Tokopedia AppTentang TokopediaMitra TokopediaMulai Berjualan PromoTokopedia CareKategori  Masuk Daftar redmi note 10shampers lebaranmeja tviphone xriphone 13android tv boxDikirim keJakarta Pusat' or . = ' Download Tokopedia AppTentang TokopediaMitra TokopediaMulai Berjualan PromoTokopedia CareKategori  Masuk Daftar redmi note 10shampers lebaranmeja tviphone xriphone 13android tv boxDikirim keJakarta Pusat')]</value>
      <webElementGuid>8c172120-9ce4-4704-839d-56da4b0b1a7b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
