<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description>Pengujian mandatory pada tab register user</description>
   <name>TS Registrasi - Mandatory</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient>yasingammarkanari@gmail.com;</mailRecipient>
   <numberOfRerun>2</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>d4dcf4db-d14b-4495-97d6-550252ae1a71</testSuiteGuid>
   <testCaseLink>
      <guid>a78c34ec-b954-413f-a052-b0d5f745dad6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/1.1. Register/TC110006</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1a5cd5f1-4bb6-49b0-8a2c-467047f5e892</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bdd5a111-4ced-49d8-9cb2-af71ef285768</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>350b8ae8-d139-4f5b-bc5f-55d1ba668c12</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3cdbab01-698e-48ef-9028-314fc9f27e15</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8be35b94-6daf-464d-baed-f27ea667aa23</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2bc80856-e6fe-4d62-a68f-49677dfc224c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/1.1. Register/TC110013</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>26cbb36e-ff84-49ca-a508-d28d1eae40b8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>df76980d-3f0b-4808-910f-72e395e34f3a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>90cd4db9-720d-4a36-a20d-f0fa382f41a9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c0595d89-1c82-45c6-b865-a90f218482c3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1d83d3db-e1a4-4565-89e3-41d4cb72f576</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
