<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Ajukan</name>
   <tag></tag>
   <elementGuidId>7e601348-884c-4858-b41f-950819be7c3f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b5-b28-Content']/div[4]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b5-b28-Content > div.padding-top-xl > div.padding-top-m</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a5bcf8bf-5d5b-4a30-84c8-ed0d6620f94e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>padding-top-m</value>
      <webElementGuid>e790abe4-34ba-44b9-9af7-5de5a030decd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ajukan </value>
      <webElementGuid>73dd96bb-09cb-4e42-8719-885009360506</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b5-b28-Content&quot;)/div[@class=&quot;padding-top-xl&quot;]/div[@class=&quot;padding-top-m&quot;]</value>
      <webElementGuid>264ae3cc-586a-44af-84ba-c1cfc5fc6e47</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b5-b28-Content']/div[4]/div</value>
      <webElementGuid>6c07453f-f529-4088-8294-9a232bf47681</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email Harus Diisi'])[1]/following::div[2]</value>
      <webElementGuid>c85f4e86-02aa-451a-b533-7bc968c0045c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email'])[2]/following::div[3]</value>
      <webElementGuid>605e02fa-ae11-47fb-84c8-627caa379f92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lacak pengajuan kamu lebih mudah dengan akun ACC ONE'])[1]/preceding::div[1]</value>
      <webElementGuid>c89fdaf4-c811-45f2-a386-3b92068011c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[3]/div/div/div/div/div[4]/div</value>
      <webElementGuid>040c1ba0-30a4-4ba8-b679-671a1392e833</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Ajukan ' or . = 'Ajukan ')]</value>
      <webElementGuid>29c3f931-3b02-4c8c-8440-b71efd32f987</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
