<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_No Handphone_b5-Input_GuestPhoneNumVar</name>
   <tag></tag>
   <elementGuidId>75a30dc6-eb2c-41b5-9405-847abc699b88</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='b5-Input_GuestPhoneNumVar']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b5-Input_GuestPhoneNumVar</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>173ea4f6-c6d3-4f19-9a1d-1e586e118d7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control OSFillParent</value>
      <webElementGuid>3853eba7-5879-495d-bf1c-5b62ffa0cc9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c2d90b42-c0e8-4368-8a0e-763b4f68b494</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>d43eef42-3de9-4e8d-b5d3-6eb190a59c2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b5-Input_GuestPhoneNumVar</value>
      <webElementGuid>7d64c782-d71c-4aee-99e1-ec93fdba7401</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b5-Input_GuestPhoneNumVar&quot;)</value>
      <webElementGuid>47415b5a-2149-440a-8833-608e7685af7f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='b5-Input_GuestPhoneNumVar']</value>
      <webElementGuid>be0cd9c5-ece6-4ef1-9817-7dffeedd9345</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b5-b30-Input']/span/input</value>
      <webElementGuid>c3a6a1c8-7718-4646-ac12-4b06627c9b96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div[2]/div[2]/div/div/div[2]/span/input</value>
      <webElementGuid>24daf00f-8aee-40f0-b6f5-665bdfa23a0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'b5-Input_GuestPhoneNumVar']</value>
      <webElementGuid>b22ca185-36ef-449b-89fd-ad0b41fd8005</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
