<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input - Email atau Nomor Handphone</name>
   <tag></tag>
   <elementGuidId>e8bc9094-294c-4402-ab5c-917fba04d66f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='b5-Input_EmailHandphoneVar']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b5-Input_EmailHandphoneVar</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8e763d28-8d3a-4b07-b5f0-8a889614e3da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control OSFillParent</value>
      <webElementGuid>58c83907-959c-4000-bc0f-b807db2b2659</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a00470d5-2371-4792-aa44-3e67b9de77b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>d728c468-970e-4270-a812-221b490f2059</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>5c401110-0cbf-4a64-a547-1bf757f22d83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b5-Input_EmailHandphoneVar</value>
      <webElementGuid>ce0f1876-af9d-4fd3-b7e8-022263014366</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b5-Input_EmailHandphoneVar&quot;)</value>
      <webElementGuid>1be471c8-2d37-40a1-a133-03d71990dbb3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='b5-Input_EmailHandphoneVar']</value>
      <webElementGuid>7c7a7d24-34d3-47bf-acae-dbf61469fd3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b5-b33-Input']/span/input</value>
      <webElementGuid>1665e054-96bc-477e-b861-e704ecdd20aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div/div/div[2]/div/div/div[2]/span/input</value>
      <webElementGuid>e4d53e03-a0a6-4798-803b-4d3f8990f7f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'b5-Input_EmailHandphoneVar']</value>
      <webElementGuid>7222b0e0-e0a5-44ce-87ae-9de32e45ee51</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
