<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>text - Belum punya akun</name>
   <tag></tag>
   <elementGuidId>68089186-83fd-4725-9404-3ab9ca95cdbc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b5-b32-Content']/div/div[6]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b5-b32-Content > div > div.padding-top-base > span.text-neutral-5</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>cd4eb285-b57e-460e-a48b-389842fb5790</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-neutral-5</value>
      <webElementGuid>789efb61-d230-43ac-a71e-30c36f2c1e62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Belum punya akun? </value>
      <webElementGuid>cba8408e-94ef-43bf-b457-58ff9d7f7a94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b5-b32-Content&quot;)/div[1]/div[@class=&quot;padding-top-base&quot;]/span[@class=&quot;text-neutral-5&quot;]</value>
      <webElementGuid>ef290739-558a-4dc2-8808-2865141bad29</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b5-b32-Content']/div/div[6]/span</value>
      <webElementGuid>f407160d-dce2-4117-aaf3-005f055540b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Masuk'])[2]/following::span[1]</value>
      <webElementGuid>da46080c-6239-4c35-b742-0564cd9e0223</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kata Sandi Harus Diisi'])[1]/following::span[1]</value>
      <webElementGuid>7c7d1c03-5553-46d8-b34a-6d331229c1b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Daftar'])[2]/preceding::span[1]</value>
      <webElementGuid>401c4dd2-fde7-4735-9497-bc75e02caf04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div/div/div[6]/span</value>
      <webElementGuid>441e533b-3f74-4ce2-ab01-3baba0397338</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Belum punya akun? ' or . = 'Belum punya akun? ')]</value>
      <webElementGuid>a3217b25-8de3-4faa-856c-28a4c4baa43b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
