<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>text button - Daftar</name>
   <tag></tag>
   <elementGuidId>ebb1d2d8-fcc3-4caf-8885-d179907460bd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b5-b32-Content']/div/div[6]/div/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.OSInline > span.text-primary</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>50a87760-23a9-410f-ae9f-d3318f036dd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-primary</value>
      <webElementGuid>d18b8ce8-6fa8-4aa5-bcab-1dd0ee493c30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Daftar</value>
      <webElementGuid>c5ac6989-a7a9-4928-b867-d101c913b369</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b5-b32-Content&quot;)/div[1]/div[@class=&quot;padding-top-base&quot;]/div[@class=&quot;OSInline&quot;]/span[@class=&quot;text-primary&quot;]</value>
      <webElementGuid>3166a93a-85ff-48fb-87ab-73344636d568</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b5-b32-Content']/div/div[6]/div/span</value>
      <webElementGuid>b98bc2d4-3c13-436a-9066-b9498806fe8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Belum punya akun?'])[2]/following::span[1]</value>
      <webElementGuid>fe911cda-02c5-415c-8b0b-c8a0ceddc425</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Masuk'])[2]/following::span[2]</value>
      <webElementGuid>90f28d7f-0bf0-49b3-97bd-58e17004e228</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/span</value>
      <webElementGuid>880e5bea-60ee-4c3e-a8b2-e20a1b36a7c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Daftar' or . = 'Daftar')]</value>
      <webElementGuid>d083354b-51e6-4d0f-afae-eb78ee3954d1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
