<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Arrow - Area Pengajuan</name>
   <tag></tag>
   <elementGuidId>87fafb88-c073-4cfc-bbdd-86708f2554d7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b5-arrow6']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b5-arrow6</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>58fcad03-ebe6-4c5a-b74b-c3c3a1518c6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>arrow</value>
      <webElementGuid>3d1f88b7-7be7-422f-89ab-aa61268554ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b5-arrow6</value>
      <webElementGuid>38609e40-ac4c-4c09-a7f3-3efd4220c48b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b5-arrow6&quot;)</value>
      <webElementGuid>dbe9a8e3-1cd6-42e4-b44b-ce7d172bb07c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='b5-arrow6']</value>
      <webElementGuid>8fb7e431-860b-4e9a-8193-f4962f8d8754</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b5-b15-Input']/div</value>
      <webElementGuid>11dcb707-bdc3-4936-aee4-d26d4c2d8f28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/div/div[2]/div</value>
      <webElementGuid>88207a8a-804b-4995-af6e-e872ccb608cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'b5-arrow6']</value>
      <webElementGuid>b07a5228-739e-4178-9053-aad585f8dfb5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
