<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_List Box OS Populer</name>
   <tag></tag>
   <elementGuidId>74bd2d01-1f50-46e9-a46b-6517e03f2674</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='header-main-wrapper']/div[2]/div/div/div[2]/div/div[2]/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.css-sbvsi7</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>4ceff3ab-495c-41e7-a08b-0ada2aa6ef3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-sbvsi7</value>
      <webElementGuid>2a7e1eaa-d54c-44a1-a08c-179e765b4f6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Apotek Generik Waringin BojonggedeHanduk PlusOscar Living OfficialMimpi SleepAndara Home Officialdc1officialABC SUN ElectronicDaihatsu Kharisma SentosaOlla Home LivingMagfit IndonesiaApotek Century Pharma Zamrud Mustika JayaToshiba Official StoreTotalEnergiesSneakers FlashRudy Project Voz Official ShopPhotobook IndonesiaPro-Hygiene SolutionRuang BettaSHELL SELECT S PARMANDAISO JAPAN OFFICIAL STORE% ARABICAMaxi phone cellHario Peak Design OfficialOnemed Rawat LukaIncase Bag &amp; CaseFirst Crack CoffeeEMINA Cheese OfficialTomiko Official StorePopoku Little Fresco Apotek PAAL 10 Kota BaruPT MastradaArmey FloristryAntik MebelGlintzGarageFORTUNE IndonesiaImpodioNature's Way IndonesiaRown Division StorealasfotopropsMax Fashions OfficialOldblue Co. Galea KitchenwareBukan Plastik89 ElectronicsAerostreetWedgwoodApotek Generik Joglo Raya KembanganSido Muncul StoreGarden Cell OfficialApotek Generik Pondok ArenHINO AUTOMOBIL BORNEOApotek Gracia Medica PadalarangMega ArviaGalesia Meat House - JakselPolo Trands Kawasaki Sumber BuanaAegis Filter OfficialCACA JakartaGasol Organik FoodsApotek Generik Utama Taman AsriSECONDATE OfficialaddawaVIP Collagen OfficialAcronis OfficialGulaliku art&amp; craft Apotek Sidikarya TabananWonderful Dry Cabinet Official StoreTri Indonesia OfficialOttoban Colis Beauty Scuto Car DetailingRejeki Toyota OfficialYAMAHA DETA MOTOR INSTANSITechwave  Bosca Livingarruzz media storeZAM CosmeticsWet N Wild Intex INOAC LivingSanDisk Best Meat Shop SurabayaAsia Global SuksesindoApotek Mitra Ciracas Jakarta TimurIvenet IndonesiaValeoTele RingHURRICANE XCS INDONESIALa Pavoni official storeAromatica IndonesiaApotek Arroz Farma 24 PringsewuHeavenly Nest Tasty GreenSenswell Transformers by Toys KingdomROUNN BagsPusat Mukena Indonesia</value>
      <webElementGuid>95898203-f74d-4418-a562-283d3045453b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header-main-wrapper&quot;)/div[@class=&quot;css-1s8dqy5 e90swyx2&quot;]/div[@class=&quot;css-1qr7rcv e1429ojz0&quot;]/div[@class=&quot;css-1iy09lx e1429ojz1&quot;]/div[@class=&quot;css-12nkv7 e1429ojz2&quot;]/div[@class=&quot;css-2fncvf-unf-tab e1429ojz3&quot;]/div[@class=&quot;css-3y7kva&quot;]/div[@class=&quot;css-sbvsi7&quot;]</value>
      <webElementGuid>9e7a098d-8cc2-486b-b452-c7acd1194559</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='header-main-wrapper']/div[2]/div/div/div[2]/div/div[2]/div[2]</value>
      <webElementGuid>9cb632d7-dcce-4211-90ad-125a5cc9c3ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lihat Semua'])[1]/following::div[1]</value>
      <webElementGuid>5b780152-924d-4040-b7b3-3bd339336793</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div[2]</value>
      <webElementGuid>ea53f226-d33c-4e6b-b4ad-1131414ec596</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = concat(&quot;Apotek Generik Waringin BojonggedeHanduk PlusOscar Living OfficialMimpi SleepAndara Home Officialdc1officialABC SUN ElectronicDaihatsu Kharisma SentosaOlla Home LivingMagfit IndonesiaApotek Century Pharma Zamrud Mustika JayaToshiba Official StoreTotalEnergiesSneakers FlashRudy Project Voz Official ShopPhotobook IndonesiaPro-Hygiene SolutionRuang BettaSHELL SELECT S PARMANDAISO JAPAN OFFICIAL STORE% ARABICAMaxi phone cellHario Peak Design OfficialOnemed Rawat LukaIncase Bag &amp; CaseFirst Crack CoffeeEMINA Cheese OfficialTomiko Official StorePopoku Little Fresco Apotek PAAL 10 Kota BaruPT MastradaArmey FloristryAntik MebelGlintzGarageFORTUNE IndonesiaImpodioNature&quot; , &quot;'&quot; , &quot;s Way IndonesiaRown Division StorealasfotopropsMax Fashions OfficialOldblue Co. Galea KitchenwareBukan Plastik89 ElectronicsAerostreetWedgwoodApotek Generik Joglo Raya KembanganSido Muncul StoreGarden Cell OfficialApotek Generik Pondok ArenHINO AUTOMOBIL BORNEOApotek Gracia Medica PadalarangMega ArviaGalesia Meat House - JakselPolo Trands Kawasaki Sumber BuanaAegis Filter OfficialCACA JakartaGasol Organik FoodsApotek Generik Utama Taman AsriSECONDATE OfficialaddawaVIP Collagen OfficialAcronis OfficialGulaliku art&amp; craft Apotek Sidikarya TabananWonderful Dry Cabinet Official StoreTri Indonesia OfficialOttoban Colis Beauty Scuto Car DetailingRejeki Toyota OfficialYAMAHA DETA MOTOR INSTANSITechwave  Bosca Livingarruzz media storeZAM CosmeticsWet N Wild Intex INOAC LivingSanDisk Best Meat Shop SurabayaAsia Global SuksesindoApotek Mitra Ciracas Jakarta TimurIvenet IndonesiaValeoTele RingHURRICANE XCS INDONESIALa Pavoni official storeAromatica IndonesiaApotek Arroz Farma 24 PringsewuHeavenly Nest Tasty GreenSenswell Transformers by Toys KingdomROUNN BagsPusat Mukena Indonesia&quot;) or . = concat(&quot;Apotek Generik Waringin BojonggedeHanduk PlusOscar Living OfficialMimpi SleepAndara Home Officialdc1officialABC SUN ElectronicDaihatsu Kharisma SentosaOlla Home LivingMagfit IndonesiaApotek Century Pharma Zamrud Mustika JayaToshiba Official StoreTotalEnergiesSneakers FlashRudy Project Voz Official ShopPhotobook IndonesiaPro-Hygiene SolutionRuang BettaSHELL SELECT S PARMANDAISO JAPAN OFFICIAL STORE% ARABICAMaxi phone cellHario Peak Design OfficialOnemed Rawat LukaIncase Bag &amp; CaseFirst Crack CoffeeEMINA Cheese OfficialTomiko Official StorePopoku Little Fresco Apotek PAAL 10 Kota BaruPT MastradaArmey FloristryAntik MebelGlintzGarageFORTUNE IndonesiaImpodioNature&quot; , &quot;'&quot; , &quot;s Way IndonesiaRown Division StorealasfotopropsMax Fashions OfficialOldblue Co. Galea KitchenwareBukan Plastik89 ElectronicsAerostreetWedgwoodApotek Generik Joglo Raya KembanganSido Muncul StoreGarden Cell OfficialApotek Generik Pondok ArenHINO AUTOMOBIL BORNEOApotek Gracia Medica PadalarangMega ArviaGalesia Meat House - JakselPolo Trands Kawasaki Sumber BuanaAegis Filter OfficialCACA JakartaGasol Organik FoodsApotek Generik Utama Taman AsriSECONDATE OfficialaddawaVIP Collagen OfficialAcronis OfficialGulaliku art&amp; craft Apotek Sidikarya TabananWonderful Dry Cabinet Official StoreTri Indonesia OfficialOttoban Colis Beauty Scuto Car DetailingRejeki Toyota OfficialYAMAHA DETA MOTOR INSTANSITechwave  Bosca Livingarruzz media storeZAM CosmeticsWet N Wild Intex INOAC LivingSanDisk Best Meat Shop SurabayaAsia Global SuksesindoApotek Mitra Ciracas Jakarta TimurIvenet IndonesiaValeoTele RingHURRICANE XCS INDONESIALa Pavoni official storeAromatica IndonesiaApotek Arroz Farma 24 PringsewuHeavenly Nest Tasty GreenSenswell Transformers by Toys KingdomROUNN BagsPusat Mukena Indonesia&quot;))]</value>
      <webElementGuid>5f59b064-bce9-496c-bfef-a310c9d8fe25</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
