<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_20</name>
   <tag></tag>
   <elementGuidId>63b3d60c-0791-456d-b168-c86d297ef3e4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b5-ListGroupArea6']/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b5-ListGroupArea6 > div.list-item</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>68960e58-cec5-4ee5-9e05-419472a559c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>list-item</value>
      <webElementGuid>7160a9df-12c1-4c8c-ad5e-14242056a805</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>51483513-d4ff-42bf-8771-df002200a820</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b5-ListGroupArea6&quot;)/div[@class=&quot;list-item&quot;]</value>
      <webElementGuid>c6535679-6c1d-4578-bef2-a57fa473f89d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b5-ListGroupArea6']/div</value>
      <webElementGuid>5347245b-485e-4b5b-aaee-23342c62b75d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DP(%)'])[1]/following::div[5]</value>
      <webElementGuid>fd51dccf-92df-4aba-94ba-38f224ee4a1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Harga OTR'])[1]/following::div[14]</value>
      <webElementGuid>6f74821a-5e6f-4f10-8018-d20e1cd71e29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tenor'])[1]/preceding::div[5]</value>
      <webElementGuid>9e127a62-84a0-4dd3-9f82-11dee95dceef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Area Pengajuan'])[1]/preceding::div[11]</value>
      <webElementGuid>2be5ba7d-c3a3-44c2-86f0-ed6f74739d51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/div[2]/div[2]/div/div</value>
      <webElementGuid>cde7e09a-2224-4c38-9863-d91bff2f2975</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '20' or . = '20')]</value>
      <webElementGuid>1698e97d-35c7-4fa2-86b8-ab09108f8972</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
