<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Login__txtUserName</name>
   <tag></tag>
   <elementGuidId>6c6b5859-b105-4dc6-a296-7acc006009d1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='_txtUserName']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;_txtUserName&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d451e00e-5b9d-4c09-8cc6-ec583cb25bbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>field</value>
      <webElementGuid>c29ab815-d5c4-4de9-9f8d-f7d773077a8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>_txtUserName</value>
      <webElementGuid>2a3c85d9-8097-475b-a528-8e71d960a363</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>224efcf5-0250-48b1-83eb-e94f10a8a7c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Username</value>
      <webElementGuid>848ea122-6064-46bd-9260-601b8100080c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tab-content2&quot;)/form[1]/input[@class=&quot;field&quot;]</value>
      <webElementGuid>e4d02076-a490-4212-946b-45d72d1944c2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='_txtUserName']</value>
      <webElementGuid>37706f36-b0d4-4e76-afa9-413c841af43e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab-content2']/form/input[2]</value>
      <webElementGuid>44cbc01f-0ae2-4986-a2e6-6417f9d4d537</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div/form/input[2]</value>
      <webElementGuid>3d58dfb1-a397-4ed3-9c95-3d634f73c578</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = '_txtUserName' and @type = 'text' and @placeholder = 'Username']</value>
      <webElementGuid>535075e3-a664-426c-b4d0-e84a39d43307</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
