<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input - No. Handphone</name>
   <tag></tag>
   <elementGuidId>b2fa139e-65e0-4cd0-89e9-b6b6d49693eb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='b5-Input_Phone']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b5-Input_Phone</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e0f3e6a4-247b-44f6-af77-debb2e713100</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control OSFillParent</value>
      <webElementGuid>eb248dde-22ed-4909-8831-948282cb8c28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>153e6bf8-e078-4a38-8b2c-cc47f5fa653e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>8d8e15ef-2326-4c36-a9c6-1919d5a1d53e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>872362755656</value>
      <webElementGuid>9e212cda-eba9-419d-8231-fcfda1dd05b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b5-Input_Phone</value>
      <webElementGuid>fe39e946-90c4-4f5f-a2c4-dd72f9e4bd12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b5-Input_Phone&quot;)</value>
      <webElementGuid>4b50a9c0-a600-4a8f-b9fd-51f2acadde0b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='b5-Input_Phone']</value>
      <webElementGuid>13e32ab0-8366-4cea-9c64-d6261d88cdd1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b5-b4-Input']/span/input</value>
      <webElementGuid>f697dcd1-04e5-472f-949e-d9d6d093b0ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/span/input</value>
      <webElementGuid>e14e1dcd-bd7b-483c-8fd0-d49c489de9f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'tel' and @id = 'b5-Input_Phone']</value>
      <webElementGuid>8ba48bf8-7c38-4755-bd20-c5b84e4b42b3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
